<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-4">
                        <h5 class="title">Atendimentos</h5>
                    </div>
                    <div class="col-md-8 ">
                        <a class="btn btn-primary float-right" href="<?= BASEURL ?>atendimentos/cadastro"><i
                                    class="fa fa-plus"></i> Atendimento
                        </a>
                    </div>
                </div>
            </div>
            <form id="filter">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="typeFilter">Tipo</label>
                            <select id="typeFilter" name="type" class="form-control">
                                <option value="0">Selecione</option>
                                <?php foreach ($typeOfService as $service): ?>
                                    <option value="<?= $service->getId() ?>"><?= $service->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="responsibleFilter">Responsável</label>
                            <select class="form-control" id="responsibleFilter" name="responsible">
                                <option value="0">Selecione</option>
                                <?php foreach ($users as $user): ?>
                                    <option value="<?= $user->getId() ?>"><?= $user->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="neighborhoodFilter">Bairro</label>
                            <select class="form-control" id="neighborhoodFilter" name="neighborhood">
                                <option value="0">Selecione</option>
                                <?php foreach ($neighborhoods as $neighborhood): ?>
                                    <option value="<?= $neighborhood->getId() ?>"><?= $neighborhood->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="institutionFilter">Instituição</label>
                            <select class="form-control" id="institutionFilter" name="institution">
                                <option value="0">Selecione</option>
                                <?php foreach ($institutions as $institution): ?>
                                    <option value="<?= $institution->getId() ?>"><?= $institution->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="statusFilter">Status</label>
                            <select id="statusFilter" name="status" class="form-control">
                                <option value="0">Selecione</option>
                                <option value="1">Pendente</option>
                                <option value="2">Resolvido</option>
                                <option value="3">Respondido/Não Atendido</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="startFilter">Dê</label>
                            <input id="startFilter" name="start" class="form-control" placeholder="dd/mm/AAAA"
                                   data-mask="99/99/9999">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="endFilter">Até</label>
                            <input id="endFilter" name="end" class="form-control" placeholder="dd/mm/AAAA"
                                   data-mask="99/99/9999">
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col text-right">
                        <button class="btn btn-warning" onclick="pdf()" ><i class="fa fa-file-pdf-o"></i>
                        </button>
                        <button class="btn btn-success" onclick="csv()" ><i class="fa fa-file-excel-o"></i>
                        </button>
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Limpar</button>
                        <button class="btn btn-primary" type="submit">Filtrar</button>
                    </div>
                </div>
            </form>
            <div class="card-body">
                <p>Exibindo <span id="partial"></span> de <span id="total"></span> </p>
                <table id="attendanceTable" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th class="text-center">Data</th>
                        <th class="text-center">Tipo</th>
                        <th class="text-center">Instituição</th>
                        <th class="text-center">Responsável</th>
                        <th class="text-center">Status</th>
                        <th class="text-center">Anexos</th>
                        <th class="text-center">Ações</th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>

    var index = partial = institution = type = responsible = status = neighborhood = start = end = 0;
    var total = 1;
    var url = urlPdf = urlCsv = '';

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        partial = 0;
        index = 0;
        total = 1;
        updateParams();
        $("#attendanceTable tbody").empty();
        generateTable();
    });

    function updateParams() {
        let formData = formDataToJson('filter');
        institution = formData.institution;
        type = formData.type;
        responsible = formData.responsible;
        status = formData.status;
        neighborhood = formData.neighborhood;
        start = formData.start;
        end = formData.end;
        urlPdf = `<?= BASEURL ?>atendimentos/pdf/?index=${index}&type=${type}&responsible=${responsible}&status=${status}&institution=${institution}&neighborhood=${neighborhood}&start=${start}&end=${end}`;
        urlCsv = `<?= BASEURL ?>atendimentos/csv/?index=${index}&type=${type}&responsible=${responsible}&status=${status}&institution=${institution}&neighborhood=${neighborhood}&start=${start}&end=${end}`;
        url = `<?= BASEURL ?>api/atendimentos/?index=${index}&type=${type}&responsible=${responsible}&status=${status}&institution=${institution}&neighborhood=${neighborhood}&start=${start}&end=${end}`;
    }

    function resetTable() {
        form.reset();
        total = 1;
        partial = index = 0;
        $("#attendanceTable tbody").empty();
        generateTable();
    }

    function attendanceView(id) {
        return `<?= BASEURL ?>atendimentos/visualizar/${id}`;
    }

    function attendanceEdit(id) {
        return `<?= BASEURL ?>atendimentos/cadastro/${id}`;
    }


    function formatAttachment(attendance) {

        return `<?= BASEURL ?>uploads/atendimentos/${attendance}`;
    }

    function generateAttendanceTable(attendance) {
        let actions = '';
        actions += `<a href="${attendanceView(attendance.id)}"><i class="fa fa-search text-info" title="Visualizar"></i></a>
                    <a href="${attendanceEdit(attendance.id)}"><i class="fa fa-pencil text-info" title="Editar"></i></a>`;
        actions = `<td class="text-center">${actions} </td>`;
        if (attendance.attendanceFile != '') {
            attendanceFile = ` <a class="btn btn-sm btn-primary" href="${formatAttachment(attendance.attendanceFile)}" target="_blank">Anexo</a> `;
        } else attendanceFile = '';
        return `<tr>
                    <td class="text-center">${attendance.date}</td>
                    <td class="text-center">${attendance.type}</td>
                    <td class="text-center">${attendance.institution}</td>
                    <td class="text-center">${attendance.user}</td>
                    <td class="text-center">${attendance.status}</td>
                    <td class="text-center">${attendanceFile}</td>
                    ${actions}
                </tr>`;
    }


    function generateTable() {
        if (total > partial) {
            updateParams();
            $('#loader').show();
            fetch(url, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#loader').hide();
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    let options = json.message.map(generateAttendanceTable);
                    $("#attendanceTable tbody").append(options);
                });
            });
        }
    }

    function pdf() {
        partial = 0;
        index = 0;
        total = 1;
        updateParams();
        window.open(urlPdf, '_blank');
    }

    function csv() {
        partial = 0;
        index = 0;
        total = 1;
        updateParams();
        window.open(urlCsv, '_blank');
    }


    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });

</script>