<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <b>Tipo do Atendimento: </b> <?= $attendance->getType()->getName()?>
            </div>
            <div class="col-md-4">
                <b>Data: </b> <?= $attendance->getDate()->format('d/m/Y') ?>
            </div>
            <div class="col-md-4">
                <b>Instituição: </b> <?= $attendance->getInstitution()->getName() ?>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col">
                <b>Bairro: </b> <?= $attendance->getNeighborhood()->getName() ?>
            </div>
            <div class="col-md-4">
                <b>Relatante: </b> <?= $attendance->getReporting() ?>
            </div>
            <div class="col-md-4">
                <b>E-mail: </b> <?= $attendance->getEmail() ?>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col">
                <b>Descrição: </b> <?= $attendance->getDescription() ?>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-4">
                <b>Responsável: </b> <?= $attendance->getResponsible()->getName() ?>
            </div>
            <div class="col-md-4">
                <b>Anexos: </b>
            </div>
        </div>
    </div>
</div>