<html>
<head>
    <meta charset="utf-8">
    <title>docPdf</title>
</head>
<body>
    <div class="row" id="header">
        <div class="col text-center">
            <?= $cabinetDetail->getHeader() ?>
        </div>
    </div>
    <div id="info">
        <div class="row">
            <div class="col">
                <?= $docs->getType()->getName() ?> nº <b>ajustar</b>
            </div>
        </div>
        <div class="row">
            <div class="col text-right">
                Angelina, <?= \App\Helpers\Utils::dateInFull($docs->getDate()->format('d/m/Y')) ?>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <?= strtoupper($docs->getInstitution()->getResponsible()) ?>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <?= $docs->getInstitution()->getName() ?>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <?= $docs->getInstitution()->getAdress() ?> - <?= $docs->getInstitution()->getNeighborhood()  ?>,
                <?= $docs->getInstitution()->getCityId()  ?> - CEP: <?= $docs->getInstitution()->getZipCode() ?>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <br>Assunto: <b><?= $docs->getSubjectMatter() ?></b>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <br><br><?= $docs->getDescription() ?>
            </div>
        </div>
        <div class="row" id="attachments" style="display: none">
            <div class="col mt-5">
                <h3 class="title text-center">Anexos</h3>
                <img src="<?= BASEURL?>uploads/documentos/<?= $docs->getImgFile() ?>">
            </div>
        </div>
    </div>
</body>
<footer>
    <div class="row">
        <div class="col text-center">
            <?= $cabinetDetail->getFooter() ?>
        </div>
    </div>
</footer>
</html>

<script>

    window.onload = function () {
        anexos();
    };


    function anexos() {

        document.getElementById('attachments').style.display = 'none';
        let anexo = <?= $docs->getImgFile() ?>;


        if (anexo.length > 0){
            document.getElementById('attachments').style.display = 'block';
        }
    }
</script>

<style>
    #header{
        line-height: 10px
    }
    #info{
        line-height: 25px
    }
    footer{
        margin-top: 8px;
        line-height: 5px;
        font-size: 10px;
        text-align: center;
    }
</style>