<div class="row">
    <div class="col">
        <div class="card p-3">
            <div class="row">
                <div class="col-md-8">
                    <h5 class="title">Clients</h5>
                </div>
                <div class="col-md-4">
                    <a class="float-right btn btn-primary text-white" href="#" onclick="openModal()"><i
                                class="fa fa-plus"></i> Client</a>
                </div>
            </div>
            <form id="filter">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="nameFilter">Name</label>
                            <input class="form-control" id="nameFilter" name="name" type="text" placeholder="Name">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="companyFilter">Company</label>
                            <input class="form-control" id="companyFilter" name="company" type="text" placeholder="Company">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="statusFilter">Status</label>
                            <select name="status" id="statusFilter" class="form-control">
                                <option value="-1">Select</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col text-right">
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Cancel</button>
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </div>
            </form>
            <p>Showing off <span id="partial"></span> of <span id="total"></span></p>
            <table class="table table-bordered table-striped" id="clientsTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th class="text-center">Name</th>
                    <th class="text-center">Company</th>
                    <th class="text-center">Email</th>
                    <th class="text-center">Phone</th>
                    <th class="text-center">Status</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody></tbody>
            </table>
            <div style="display: none" id="message" class="alert alert-danger" role="alert"></div>
        </div>
    </div>
</div>

<!-- Modal Cadastro-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Client registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addClient" method="post">
                <div class="form-group">
                    <input type="hidden" name="clientId" id="clientId">
                    <div class="row">
                        <div class="col">
                            <label for="name">Name</label>
                            <input id="name" name="name" class="form-control" type="text" placeholder="Name">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="company">Company</label>
                            <input id="company" name="company" class="form-control" type="text" placeholder="Company">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="email">Email</label>
                            <input id="email" name="email" class="form-control" type="email" placeholder="Email">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="phone">Phone</label>
                            <input id="phone" name="phone" class="form-control" type="text"
                                   placeholder="+99 99 9999-9999" onfocus="mTel()">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="office">Office</label>
                            <input id="office" name="office" class="form-control" type="text" placeholder="Office">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save Client</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>

    function openModal() {
        $('#modal').modal('show');
        $('#message').hide();
        document.getElementById('addClient').reset();
    }

    function openModalEdit(id) {

        document.getElementById('addClient').reset();
        document.getElementById('clientId').value = id;
        $('#modal').modal('show');
        $('#message').hide();
        if (id > 0) {
            showLoading();
            fetch(`<?= BASEURL ?>clients/api/${id}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    json = json.message[0];
                    closeLoading();
                    document.getElementById('email').value = json.email;
                    document.getElementById('company').value = json.company;
                    document.getElementById('name').value = json.name;
                    document.getElementById('phone').value = json.phone;
                    document.getElementById('office').value = json.office;
                });
            });
        }
    }

    const formAdd = document.getElementById('addClient');
    const divMessage = document.getElementById('message');

    formAdd.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let formData = formDataToJson('addClient');
        fetch("<?= BASEURL ?>clients/register", {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            closeLoading();
            divMessage.classList.add("alert-danger");
            divMessage.classList.remove("alert-success");
            response.json().then(json => {
                divMessage.textContent = json.message;
                divMessage.style.display = 'block';
                if (response.status === 201) {
                    $('#modal').modal('hide');
                    divMessage.classList.add("alert-success");
                    divMessage.classList.remove("alert-danger");
                    formAdd.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    var index = 0;
    var partial = 0;
    var total = 1;
    var status = -1;
    var name = 0;
    var company = 0;

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        name = formData.name;
        company = formData.company;
        type = formData.type;
        $("#clientsTable tbody").empty();
        generateTable();
    });

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        status = -1;
        name = 0;
        company = 0;
        $("#clientsTable tbody").empty();
        generateTable();
    }

    function generateClientsTable(client) {
        let actions = '';
        actions += `<i class="fa fa-pencil text-info" title="Editar" onclick="openModalEdit(${client.id})"></i> `;
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td class="text-center">${client.name}</td>
                    <td class="text-center">${client.company}</td>
                    <td class="text-center">${client.email}</td>
                    <td class="text-center">${client.phone}</td>
                    <td class="text-center">${client.status}</td>
                    ${actions}
                </tr>`;
    }

    function generateTable() {
        if (total > partial) {
            $('#loader').show();
            fetch(`<?= BASEURL ?>clients/api/?index=${index}&name=${name}&company=${company}&status=${status}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#loader').hide();
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    let options = json.message.map(generateClientsTable);
                    $("#clientsTable tbody").append(options);
                });
            });
        }
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });

</script>
