
</div>
<!-- Modal -->
<div class="modal fade" id="showLoading" tabindex="-1" role="dialog" aria-labelledby="showLoading">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-body text-center">
                <div class="loader"></div>
                <div clas="loader-txt">
                </div>
            </div>
        </div>
    </div>
</div>

<footer class="footer">
    <div class="container-fluid text-center">
        ©
        <script>
            document.write(new Date().getFullYear());</script
        >, feito com <i class="fa fa-heart heart"></i> by <a href="https://www.lifecode.dev/" class="text-yellow" target="_blank">Life Code</a>
    </div>
</footer>
</div>
</div>

<!--   Core JS Files   -->
<script defer src="<?= BASEURL ?>assets/js/functions.js"></script>
/<script src="<?= BASEURL ?>assets/js/core/popper.min.js"></script>
<script src="<?= BASEURL ?>assets/js/core/bootstrap.min.js"></script>
<script src="<?= BASEURL ?>assets/js/plugins/bootstrap-notify.js"></script>
<script src="<?= BASEURL ?>assets/js/paper-dashboard.min.js?v=2.0.0"></script>
<script src="<?= BASEURL ?>assets/js/jquery.mask.min.js"></script>
<script defer src="<?= BASEURL ?>assets/js/jquery.dataTables.min.js"></script>
<script defer src="<?= BASEURL ?>assets/js/dataTables.bootstrap4.min.js"></script>
</body>
</html>