<form method="post" enctype="multipart/form-data" id="form">
    <div class="row">
        <div class="col-md-1">
            <div class="form-group">
              <span class="fileselector">
                  <label class="btn btn-danger" for="img">
                      <input class="upload-file-selector" required id="img" type="file" name="img">
                      <i class="fa fa-paperclip margin-correction"></i> Nova Imagem
                  </label>
              </span>
            </div>
        </div>
        <div class="col-md-1" id="sendImg" style="display: none">
            <button type="submit" class="btn btn-success">Enviar</button>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div style="display: none" id="messageForm" class="alert" role="alert"></div>
        </div>
    </div>
</form>

<div class="row">

    <?php foreach ($images as $image): ?>

        <div class="col-md-2">
            <div class="card text-center">
                <img src="<?= BASEURL . 'uploads/imagens/' . $image->getImgFile() ?>" alt="aa">
                <button class="btn btn-outline-success btn-sm" data-clipboard-text="<?= BASEURL . 'uploads/imagens/' . $image->getImgFile() ?>">
                    Copiar Link
                </button>
            </div>
        </div>

    <?php endforeach; ?>


</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js"></script>
<script>
    var clipboard = new ClipboardJS('.btn');
    clipboard.on('success', function (e) {
        alert('Imagem copiada')
        e.clearSelection();
    });


    $('#img').change(function (e) {
        let input = e.target;
        input.parentElement.classList.remove('btn-primary');
        input.parentElement.classList.add('btn-danger');
        $('#sendImg').hide();
        if (input.files.length > 0) {
            input.parentElement.classList.remove('btn-danger');
            input.parentElement.classList.add('btn-primary');
            $('#sendImg').show();
        }
    });

    const formAdd = document.getElementById('form');
    const divMessageForm = document.getElementById('messageForm');

    formAdd.addEventListener('submit', e => {
        $('#save').addClass('disabled');
        e.preventDefault();
        showLoading();
        let method = 'POST';
        let formData = formDataToJson('form');
        fetch("<?= BASEURL ?>galeria/cadastro", {
            method: method,
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json'
            },
            body: new FormData(formAdd)
        }).then(response => {
            closeLoading();
            divMessageForm.classList.add("alert-danger");
            divMessageForm.classList.remove("alert-success");
            $('#save').removeClass('disabled');
            response.json().then(json => {
                divMessageForm.textContent = json.message;
                divMessageForm.style.display = 'block';
                if (response.status === 201) {
                    divMessageForm.classList.add("alert-success");
                    divMessageForm.classList.remove("alert-danger");
                    formAdd.reset();
                    setTimeout(function () {
                        window.location.href = "<?= BASEURL ?>galeria";
                    }, 2000);
                }
            });
        });
    });

    $(document).ready(function () {
        $('input:file').change(function (e) {
            let input = e.target;

            if (input.files.length > 0) {
                input.parentElement.classList.remove('btn-primary');
                input.parentElement.classList.remove('btn-danger');
                input.parentElement.classList.add('btn-success');
            } else {
                input.parentElement.classList.remove('btn-success');
                input.parentElement.classList.add('btn-danger');
            }
        });
    });

</script>