<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale = 1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/libs/font-awesome/css/font-awesome.min.css">
    <link rel="icon" href="<?= BASEURL ?>assets/img/sisgg.png">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>Excent - Admin</title>
    <link href="<?= BASEURL ?>assets/css/paper-dashboard.css?v=2.0.0" rel="stylesheet"/>
    <script src="<?= BASEURL ?>assets/js/core/jquery.min.js"></script>
    <link rel="icon" href="<?= BASEURL ?>assets/img/icon.png">
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/style.css">
    <script src="https://kit.fontawesome.com/b1f34ab4bc.js" crossorigin="anonymous"></script>
</head>

<body>
<div class="wrapper">
    <div class="sidebar" data-color="dark">
        <div class="logo">
            <a href="<?= BASEURL ?>" class="simple-text text-center logo-normal">
                <img class="img-fluid" style="max-height: 80px" src="<?= BASEURL ?>assets/img/logobranco.png">
            </a>
        </div>
        <div class="sidebar-wrapper">
            <ul class="nav" style="overflow-x: hidden">

                <li <?= in_array('dashboard', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>">
                        <i class="fa fa-dashboard"></i> <b>Dashboard</b>
                    </a>
                </li>
                <?php if ($user->getType() == 1): ?>
                <li <?= in_array('transactions', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>transactions">
                        <i class="fa fa-money-bill-wave"></i> <b>Transactions</b>
                    </a>
                </li>
                <?php endif; ?>
                <li <?= in_array('deals', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>deals">
                        <i class="fa fa-dollar"></i> <b>Deals</b>
                    </a>
                </li>
                <li <?= in_array('leads', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>leads">
                        <i class="fa fa-crosshairs"></i> <b>Leads</b>
                    </a>
                </li>
                <li <?= in_array('users', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>users">
                        <i class="fa fa-users"></i> <b>Users</b>
                    </a>
                </li>
                <li <?= in_array('documents', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>documents">
                        <i class="fa fa-file"></i> <b>Documents</b>
                    </a>
                </li>
                <li <?= in_array('messages', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>messages">
                        <i class="fa fa-envelope"></i> <b>Messages</b>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-absolute fixed-top bg-custom-2">
            <div class="container-fluid">

                <div class="navbar-wrapper">
                    <div class="navbar-toggle">
                        <button type="button" class="navbar-toggler">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </button>
                    </div>
                    <a class="navbar-brand" href="#" onclick="openModalUser()" style="z-index: 100">
                        <b><?= $user->getName() ?></b> <i class="fa fa-cog"></i>
                    </a>
                </div>
                <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navigation"
                        aria-controls="navigation-index"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navigation">
                    <ul class="navbar-nav">
                        <li class="nav-item btn-rotate dropdown">
                            <a class="nav-link btn btn-sm btn-danger" href="<?= BASEURL ?>logout">Logout</a>
                        </li>
                        <li class="nav-item btn-rotate dropdown">
                            <a class="nav-link btn btn-sm btn-primary text-white" onclick="openRemember()">Remember</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End Navbar -->

        <div class="content">

            <?php if (\App\Helpers\Session::get('errorMsg')): ?>
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        <div class="alert alert-danger"><?= \App\Helpers\Session::get('errorMsg') ?></div>
                    </div>
                    <div class="col-md-3"></div>
                </div>
                <?php \App\Helpers\Session::forgot('errorMsg'); ?>
            <?php endif; ?>
            <!-- Modal Remember-->
            <div class="modal right fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-top">
                            <div class="row">
                                <div class="col-md-5 mt-0">
                                    <h4 class="modal-title" id="myModalLabel">New Task</h4>
                                </div>
                                <div class="col float-right my-auto">
                                    <i class="close fa-2x fa fa-chevron-circle-right text-white" data-dismiss="modal"
                                       aria-label="Close">
                                    </i>
                                </div>
                            </div>
                        </div>
                        <div class="modal-body">
                            <form id="formTask">
                                <div class="row">
                                    <div class="col">
                                        <label for="dealId">Lead</label>
                                        <select id="dealId" name="dealId" class="form-control">
                                            <option value="0">Select lead</option>
                                            <?php foreach ($deals as $deal): ?>
                                            <option value="<?= $deal->getId() ?>"><?= $deal->getName() ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <label for="activity">Activity</label>
                                        <input name="activity" id="activity" placeholder="Activity" class="form-control mb-1">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <div class="btn-group btn-group-toggle" data-toggle="buttons">
                                            <label class="btn btn-white active" title="Call">
                                                <input type="radio" name="options" id="hatchback" autocomplete="off" value="2"
                                                       checked >
                                                <i class="fa fa-phone text-gray"></i>
                                            </label>
                                            <label class="btn btn-white" title="Meeting">
                                                <input type="radio" name="options" id="sedan" autocomplete="off" value="3">
                                                <i class="fa fa-users text-gray" ></i>
                                            </label>
                                            <label class="btn btn-white" title="Email">
                                                <input type="radio" name="options" id="suv" autocomplete="off" value="4">
                                                <i class="fa fa-paper-plane text-gray" ></i>
                                            </label>
                                            <label class="btn btn-white" title="Launch">
                                                <input type="radio" name="options" id="suv" autocomplete="off" value="5">
                                                <i class="fa fa-utensils text-gray" ></i>
                                            </label>
                                            <label class="btn btn-white" title="Task">
                                                <input type="radio" name="options" id="suv" autocomplete="off" value="6">
                                                <i class="fa fa-clock text-gray" ></i>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="date">Date</label>
                                        <input name="date" id="date" placeholder="dd/mm/YYYY" data-mask="99/99/9999"
                                               class="form-control mb-1">
                                    </div>
                                    <div class="col-md-6">
                                        <label for="time">Time</label>
                                        <input name="time" id="time" placeholder="HH:ii" data-mask="99:99"
                                               class="form-control mb-1">
                                    </div>
                                </div>
<!--                                <div class="row">-->
<!--                                    <div class="col">-->
<!--                                        <label for="description">Description</label>-->
<!--                                        <textarea name="description" id="description" placeholder="Description"-->
<!--                                                  class="form-control mb-1"></textarea>-->
<!--                                    </div>-->
<!--                                </div>-->
                                <input name="status" id="status" type="hidden" value="1">
                                <div class="row">
                                    <div class="col text-right">
                                        <button type="submit" class="btn btn-primary">Save Activity</button>
                                    </div>
                                </div>
                            </form>
                            <div style="display: none" id="messageTask" class="alert alert-danger" role="alert"></div>
                        </div>
                    </div><!-- modal-content -->
                </div><!-- modal-dialog -->
            </div><!-- modal -->

            <!-- Modal User-->
            <div class="modal right fade" id="myUser" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-top">
                            <div class="row">
                                <div class="col-md-5 mt-0">
                                    <h4 class="modal-title" id="myModalLabel">Edit User</h4>
                                </div>
                                <div class="col float-right my-auto">
                                    <i class="close fa-2x fa fa-chevron-circle-right text-white" data-dismiss="modal"
                                       aria-label="Close">
                                    </i>
                                </div>
                            </div>
                        </div>
                        <div class="modal-body">
                            <form id="editUser" method="post">
                                <div class="form-group">
                                    <input type="hidden" name="userId" id="userId">
                                    <div class="row">
                                        <div class="col">
                                            <label for="name">Name</label>
                                            <input id="name" name="name" class="form-control" type="text"
                                                   placeholder="Name" value="<?= $user->getName() ?>">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <label for="email">Email</label>
                                            <input id="email" name="email" class="form-control" type="email"
                                                   placeholder="Email" value="<?= $user->getEmail() ?>">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <label for="password">Password</label>
                                            <input id="password" name="password" class="form-control" type="text"
                                                   placeholder="Password">
                                            <span style="font-size: 8px; color: grey; margin-left: 5px">Minimum 8 characters</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col text-right">
                                        <button type="submit" class="btn btn-primary">Edit User</button>
                                    </div>
                                </div>
                            </form>
                            <div style="display: none" id="messageUser" class="alert alert-danger" role="alert"></div>
                        </div>
                    </div><!-- modal-content -->
                </div><!-- modal-dialog -->
            </div><!-- modal -->
            <script>
                function openRemember() {
                    $('#myModal').modal('show');
                }

                function openModalUser() {
                    $('#myUser').modal('show');
                }

                const formAddTask = document.getElementById('formTask');
                const divMessageTask = document.getElementById('messageTask');

                formAddTask.addEventListener('submit', e => {
                    e.preventDefault();
                    showLoading();
                    let formData = formDataToJson('formTask');
                    fetch("<?= BASEURL ?>deals/activity/register", {
                        method: 'POST',
                        credentials: 'same-origin',
                        headers: {
                            'Accept': 'application/json',
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify(formData)
                    }).then(response => {
                        closeLoading();
                        divMessageTask.classList.add("alert-danger");
                        divMessageTask.classList.remove("alert-success");
                        response.json().then(json => {
                            divMessageTask.textContent = json.message;
                            divMessageTask.style.display = 'block';
                            if (response.status === 201) {
                                $('#modal').modal('hide');
                                divMessageTask.classList.add("alert-success");
                                divMessageTask.classList.remove("alert-danger");
                                formAddTask.reset();
                                setTimeout(function () {
                                    location.reload();
                                }, 1500);
                            }
                        });
                    });
                });

                const formEditUser = document.getElementById('editUser');
                const divMessageUser = document.getElementById('messageUser');

                formEditUser.addEventListener('submit', e => {
                    e.preventDefault();
                    showLoading();
                    let formData = formDataToJson('editUser');
                    fetch(`<?= BASEURL ?>users/edit/<?= $user->getId() ?>`, {
                        method: 'POST',
                        credentials: 'same-origin',
                        headers: {
                            'Accept': 'application/json',
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify(formData)
                    }).then(response => {
                        closeLoading();
                        divMessageUser.classList.add("alert-danger");
                        divMessageUser.classList.remove("alert-success");
                        response.json().then(json => {
                            divMessageUser.textContent = json.message;
                            divMessageUser.style.display = 'block';
                            if (response.status === 201) {
                                $('#modal').modal('hide');
                                divMessageUser.classList.add("alert-success");
                                divMessageUser.classList.remove("alert-danger");
                                formEditUser.reset();
                                setTimeout(function () {
                                    location.reload();
                                }, 1500);
                            }
                        });
                    });
                });


            </script>
