<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale = 1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/libs/font-awesome/css/font-awesome.min.css">
    <link rel="icon" href="<?= BASEURL ?>assets/img/sisgg.png">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>Excent - Admin</title>
    <link href="<?= BASEURL ?>assets/css/paper-dashboard.css?v=2.0.0" rel="stylesheet"/>
    <script src="<?= BASEURL ?>assets/js/core/jquery.min.js"></script>
    <link rel="icon" href="<?= BASEURL ?>assets/img/icon.png">
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/style.css">
    <script src="https://kit.fontawesome.com/b1f34ab4bc.js" crossorigin="anonymous"></script>
</head>

<body>
<div class="wrapper">
    <div class="sidebar" data-color="dark" data-active-color="success">
        <div class="logo">
            <a href="<?= BASEURL ?>" class="simple-text text-center logo-normal">
                <img class="img-fluid" style="max-height: 50px" src="<?= BASEURL ?>assets/img/logo.jpeg">
            </a>
        </div>
        <div class="sidebar-wrapper">
            <ul class="nav" style="overflow-x: hidden">

                <li <?= in_array('dashboard', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>">
                        <i class="fa fa-dashboard"></i> Dashboard
                    </a>
                </li>
                <li <?= in_array('deals', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>deals">
                        <i class="fa fa-dollar"></i> Deals
                    </a>
                </li>
                <li <?= in_array('users', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>users">
                        <span class="sidebar-normal"><i class="fa fa-users"></i> Users</span>
                    </a>
                </li>
                <li <?= in_array('documents', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>documents">
                        <span class="sidebar-normal"><i class="fa fa-file"></i> Documents</span>
                    </a>
                </li>
                <li <?= in_array('messages', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>messages">
                        <span class="sidebar-normal"><i class="fa fa-envelope"></i> Messages</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
            <div class="container-fluid">
                <div class="navbar-wrapper">
                    <div class="navbar-toggle">
                        <button type="button" class="navbar-toggler">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </button>
                    </div>
                    <a class="navbar-brand" href="#">
                        <?= $user->getName() ?>
                    </a>
                </div>
                <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navigation"
                        aria-controls="navigation-index"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navigation">
                    <ul class="navbar-nav">
                        <li class="nav-item btn-rotate dropdown">
                            <a class="nav-link btn btn-sm btn-danger" href="<?= BASEURL ?>logout">Logout</a>
                        </li>
                        <li class="nav-item btn-rotate dropdown">
                            <a class="nav-link btn btn-sm btn-primary text-white" onclick="openRemember()">Remember</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End Navbar -->

        <div class="content">

            <?php if (\App\Helpers\Session::get('errorMsg')): ?>
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        <div class="alert alert-danger"><?= \App\Helpers\Session::get('errorMsg') ?></div>
                    </div>
                    <div class="col-md-3"></div>
                </div>
                <?php \App\Helpers\Session::forgot('errorMsg'); ?>
            <?php endif; ?>
            <!-- Modal -->
            <div class="modal right fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-top">
                            <div class="row">
                                <div class="col-md-10 mt-3">
                                    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-plus"></i> New Task</h4>
                                </div>
                                <div class="col-md-2 float-right mt-5">
                                    <i class="close fa-2x fa fa-chevron-circle-right text-white" data-dismiss="modal"
                                       aria-label="Close">
                                    </i>
                                </div>
                            </div>
                        </div>
                        <div class="modal-body">
                            <form id="formTask">
                                <div class="form-group">
                                    <div class="row mt-4">
                                        <div class="col-md-6">
                                            <label for="date">Date</label>
                                            <input class="form-control" id="date" name="date" type="text" placeholder="dd/mm/YYYY"
                                                   required data-mask="99/99/9999">
                                        </div>
                                        <div class="col-md-6">
                                            <label for="time">Time</label>
                                            <input class="form-control" id="time" name="time" type="text" placeholder="HH:ii" data-mask="99:99">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <label for="action">Action</label>
                                            <select class="form-control" id="action" name="action" required>
                                                <option value="0">Select</option>
                                                <option value="1">Call</option>
                                                <option value="2">Meeting</option>
                                                <option value="3">Email</option>
                                                <option value="4">Lunch</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <label for="client">Client</label>
                                            <select class="form-control" id="client" name="client" required>
                                                <option value="0">Select</option>
                                                <?php foreach ($clients as $client): ?>
                                                    <option value="<?= $client->getId() ?>"><?= $client->getName() ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <label for="description">Description</label>
                                            <textarea class="form-control" id="description" name="description" placeholder="Description"
                                                      type="text"></textarea>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col text-right">
                                            <button type="submit" class="btn btn-primary">Save Task</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <div style="display: none" id="messageTask" class="alert alert-danger" role="alert"></div>
                        </div>
                    </div><!-- modal-content -->
                </div><!-- modal-dialog -->
            </div><!-- modal -->
            <script>
                function openRemember() {
                    $('#myModal').modal('show');
                }

                const formAddTask = document.getElementById('formTask');
                const divMessageTask = document.getElementById('messageTask');

                formAddTask.addEventListener('submit', e => {
                    e.preventDefault();
                    showLoading();
                    let formData = formDataToJson('formTask');
                    fetch("<?= BASEURL ?>task/register", {
                        method: 'POST',
                        credentials: 'same-origin',
                        headers: {
                            'Accept': 'application/json',
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify(formData)
                    }).then(response => {
                        closeLoading();
                        divMessageTask.classList.add("alert-danger");
                        divMessageTask.classList.remove("alert-success");
                        response.json().then(json => {
                            divMessageTask.textContent = json.message;
                            divMessageTask.style.display = 'block';
                            if (response.status === 201) {
                                $('#modal').modal('hide');
                                divMessageTask.classList.add("alert-success");
                                divMessageTask.classList.remove("alert-danger");
                                formAddTask.reset();
                                setTimeout(function () {
                                    location.reload();
                                }, 1500);
                            }
                        });
                    });
                });

            </script>
