<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale = 1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/libs/font-awesome/css/font-awesome.min.css">
    <link rel="icon" href="<?= BASEURL ?>assets/img/sisgg.png">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>Excent - Admin</title>
    <link href="<?= BASEURL ?>assets/css/paper-dashboard.css?v=2.0.0" rel="stylesheet"/>
    <script src="<?= BASEURL ?>assets/js/core/jquery.min.js"></script>
    <link rel="icon" href="<?= BASEURL ?>assets/img/icon.png">
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/style.css">
</head>

<body>
<div class="wrapper">
    <div class="sidebar" data-color="dark" data-active-color="success">
        <div class="logo">
            <a href="<?= BASEURL ?>" class="simple-text text-center logo-normal">
                <img class="img-fluid" style="max-height: 50px" src="<?= BASEURL ?>assets/img/logo.jpeg">
            </a>
        </div>
        <div class="sidebar-wrapper">
            <ul class="nav" style="overflow-x: hidden">

                <li <?= in_array('dashboard', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>">
                        <i class="fa fa-dashboard"></i>Dashboard
                    </a>
                </li>
                <li <?= in_array('users', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>users">
                        <span class="sidebar-normal"><i class="fa fa-users"></i>Users</span>
                    </a>
                </li>
                <li <?= in_array('clients', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>clients">
                        <span class="sidebar-normal"><i class="fa fa-briefcase"></i>Clients</span>
                    </a>
                </li>
                <li <?= in_array('documents', $menuActive) ? 'class="active"' : '' ?>>
                    <a href="<?= BASEURL ?>documents">
                        <span class="sidebar-normal"><i class="fa fa-file"></i>Documents</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
            <div class="container-fluid">
                <div class="navbar-wrapper">
                    <div class="navbar-toggle">
                        <button type="button" class="navbar-toggler">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </button>
                    </div>
                    <a class="navbar-brand" href="#">
                        <?= $user->getName() ?>
                    </a>
                </div>
                <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navigation"
                        aria-controls="navigation-index"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navigation">
                    <ul class="navbar-nav">
                        <li class="nav-item btn-rotate dropdown">
                            <a class="nav-link btn btn-sm btn-danger" href="<?= BASEURL ?>logout">Logout</a>
                        </li>
                        <li class="nav-item btn-rotate dropdown">
                            <a class="nav-link btn btn-sm btn-primary text-white">Remember</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End Navbar -->

        <div class="content">

            <?php if (\App\Helpers\Session::get('errorMsg')): ?>
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <div class="alert alert-danger"><?= \App\Helpers\Session::get('errorMsg') ?></div>
                </div>
                <div class="col-md-3"></div>
            </div>
            <?php \App\Helpers\Session::forgot('errorMsg'); ?>
<?php endif; ?>