<div class="row">
    <div class="col-md-6">
        <div class="card p-3" style="height: 90%">
            <div class="row" style="height: 100%">
                <div class="col" >
                    <div class="row">
                        <i class=" fa fa-2x fa-medal"> </i> <h5 class="title ml-3"> Leader Board</h5>
                    </div>
                    <div class="row mb-4">
                        <div class="col">
                            Resumo do Ranking
                        </div>
                    </div>
                    <div style="position: absolute; bottom: 0; right: 0">
                        <a onclick="openModalRanking()" href="#">View more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card p-3" style="height: 90%">
            <div class="row" style="height: 100%">
                <div class="col">
                    <div class="row">
                        <i class=" fa fa-2x fa-clock"> </i> <h5 class="title ml-3"> Tasks</h5>
                    </div>
                    <div class="row mb-4">
                        <div class="col">
                            Descrição de tarefas diárias agrupadas por tipo:<br>
                            2 call;<br>
                            3 e-mails;<br>
                            1 meeting;<br>
                        </div>
                    </div>
                    <div style="position: absolute; bottom: 0; right: 0">
                        <a href="#" >View more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="card p-3" style="height: 90%">
            <div class="row" style="height: 100%">
                <div class="col" style="position: relative">
                    <div class="row">
                        <i class=" fa fa-2x fa-envelope"> </i> <h5 class="title ml-3"> Messages</h5>
                    </div>
                    <div class="row mb-4">
                        <div class="col">
                            Aparece as três últimas mensagens recebidas
                        </div>
                    </div>
                    <div style="position: absolute; bottom: 0; right: 0;">
                        <a href="#" >View more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card p-3" style="height: 90%">
            <div class="row" style="height: 100%">
                <div class="col">
                    <div class="row">
                        <i class=" fa fa-2x fa-file"> </i> <h5 class="title ml-3"> Documents</h5>
                    </div>
                    <div class="row mb-4">
                        <div class="col">
                            Aparece as três últimas documentos recebidos
                        </div>
                    </div>
                    <div style="position: absolute; bottom: 0; right: 0">
                        <a href="#" >View more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal Ranking-->
<div class="modal fade" id="modalRanking" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">User Registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <?php if ($user->getType() == 1 || $user->getType() == 2 || $user->getType() == 3): ?>
                <div class="row mt-4">
                    <div class="col">
                        <ul class="nav nav-tabs nav-justified">
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#managers">Managers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#managersGroup">Group of Manager</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#advisors">Advisors</a>
                            </li>
                        </ul>
                    </div>
                </div>
            <?php endif; ?>
            <div class="card-body">
                <div class="tab-content">
                    <div class="tab-pane container active" id="advisors">
                        <div class="row">
                            <div class="col">
                                <table class="table table-sm table-hover" id="advRanking">
                                    <thead>
                                    <tr>
                                        <th scope="col" class="text-center">#</th>
                                        <th scope="col" class="text-center">User</th>
                                        <th scope="col" class="text-center">Country</th>
                                        <th scope="col" class="text-center">New Accounts</th>
                                        <th class="text-center" scope="col">New Deposits</th>
                                        <th scope="col" class="text-center">Withdrawals</th>
                                        <th class="text-center" scope="col">Net Margin In</th>
                                    </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane container" id="managers">
                        <div class="row">
                            <div class="col">
                                <table class="table table-sm table-hover" id="managersTable">
                                    <thead>
                                    <tr>
                                        <th scope="col" class="text-center">#</th>
                                        <th scope="col" class="text-center">User</th>
                                        <th scope="col" class="text-center">Country</th>
                                        <th scope="col" class="text-center">New Accounts</th>
                                        <th class="text-center">New Deposits</th>
                                        <th scope="col" class="text-center">Withdrawals</th>
                                        <th class="text-center">Net Margin In</th>
                                    </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane container" id="managersGroup">
                        <div class="row">
                            <div class="col">
                                <table class="table table-sm table-hover" id="managersGroupTable">
                                    <thead>
                                    <tr>
                                        <th scope="col" class="text-center">#</th>
                                        <th scope="col" class="text-center">User</th>
                                        <th scope="col" class="text-center">Country</th>
                                        <th scope="col" class="text-center">New Accounts</th>
                                        <th class="text-center">New Deposits</th>
                                        <th scope="col" class="text-center">Withdrawals</th>
                                        <th class="text-center">Net Margin In</th>
                                    </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>





<!--<div class="row">-->
<!--    <div class="col">-->
<!--        --><?php //if ($messages != null): ?>
<!--        <div class="card p-3">-->
<!--            <div class="row">-->
<!--                <div class="col-md-8">-->
<!--                    <h5 class="title">Messages</h5>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="card-body" id="messagesDiv">-->
<!---->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<?php //endif; ?>
<!--<div class="row">-->
<!--    <div class="col">-->
<!--        --><?php //if ($tasks != null): ?>
<!--            <div class="card p-3">-->
<!--                <div class="row">-->
<!--                    <div class="col-md-8">-->
<!--                        <h5 class="title">Tasks</h5>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="card-body">-->
<!--                    <div class="row" id="tasksDiv"></div>-->
<!---->
<!--                </div>-->
<!--            </div>-->
<!--        --><?php //endif; ?>
<!--    </div>-->
<!--</div>-->

<script>

    var index = 0;

    function openModalRanking() {
        $('#modalRanking').modal('show');
    }

    function generateMessagesCard(message) {
        return `<div class="bg-white p-3 mb-4" style="border: solid 1px rgb(0, 0, 0, 0.25);">
                    <div class="col">
                        <div class="row">
                            <div class="col-md-11" data-toggle="collapse" data-target="#collapse${message.id}" aria-expanded="false" aria-controls="collapse${message.id}">
                                <h6 class="my-auto">
                                      ${message.title}
                                </h6>
                            </div>
                            <div class="col-md-1 text-right">
                                <a><i class="fa fa-check-circle" id="iconCheck"></i></a>
                            </div>
                        </div>
                        <div class="row mt-2">
                                <div class="col" style="font-size: 12px">
                                    <i class="fa fa-calendar"></i> ${message.date}
                                    <i class="fa fa-clock-o ml-2"></i> ${message.time}
                                    <i class="fa fa-user ml-2"></i> ${message.user}
                                </div>
                            </div>
                        <div class="row">
                            <div id="collapse${message.id}" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                              <div class="card-body text-justify">
                                ${message.description}
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
        `;
    }

    function generateMessages() {
        $('#loader').show();
        fetch(`<?= BASEURL ?>dashboard/messages/api/?index=${index}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                $('#loader').hide();
                let options = json.message.map(generateMessagesCard);
                $("#messagesDiv").append(options);
            });
        });

    }

    function generateTasksCard(task) {
        let time = '';
        if (task.time != null) time = `${task.time}:`;
        return `<div class="col-md-4 my-2" id="cardTask${task.id}">
                    <div class="row bg-white p-3 card-task">
                        <div class="col-md-4 my-auto">
                            ${actionIcon(task.type)}
                        </div>
                        <div class="col-md-8 card-date">
                            <div class="row">
                                <div class="col"> <b>${time} ${actionStr(task.type)}</b></div>
                            </div>
                            <div class="row">
                                <div class="col"> ${task.deal}</div>
                            </div>
                            <div class="row">
                                <div class="col-md-9"></div>
                                <div class="col-md-3 text-right" onclick="taskStatus(${task.id})"><a><i class="fa fa-check-circle" id="iconCheck"></i></a></div>
                            </div>
                        </div>
                    </div>
                </div>`;
    }

    function actionStr(action) {
        switch (parseInt(action)) {
            case 2:
                return 'Call';
            case 3:
                return 'Meeting';
            case 4:
                return 'Email';
            case 5:
                return 'Lunch';
            case 6:
                return 'Task';
            default:
                return 'Unknown';

        }
    }

    function actionIcon(action) {
        switch (parseInt(action)) {
            case 2:
                return `<i class="fa fa-3x fa-phone text-gray"></i>`;
            case 3:
                return `<i class="fa fa-3x fa-users text-gray"></i>`;
            case 4:
                return `<i class="fa fa-3x fa-paper-plane text-gray"></i>`;
            case 5:
                return `<i class="fa fa-3x fa-utensils text-gray"></i>`;
            case 6:
                return `<i class="fa fa-3x fa-clock text-gray"></i>`;
            default:
                return `<i class="fa fa-3x fa-phone text-gray"></i>`;
        }
    }

    function viewFlag(flag) {
        let destiny = `<?= BASEURL ?>${flag}`;
        return `<img src="${destiny}">`;
    }

    function generateRankingTable(transaction) {

        return `<tr>
                    <td class="text-center" scope="row"></td>
                    <td class="text-center">${transaction.user}</td>
                    <td class="text-center">${viewFlag(transaction.country)}</td>
                    <td class="text-center">${transaction.accounts}</td>
                    <td class="text-center">${maskMoneyTable(transaction.totalDeposit)}</td>
                    <td class="text-center">${maskMoneyTable(transaction.totalCapture)}</td>
                    <td class="text-center">${maskMoneyTable(transaction.marginIn)}</td>
                </tr>
        `;
    }

    function generateRankingAdvisors() {
        $('#loader').show();
        fetch(`<?= BASEURL ?>dashboard/transations/advisors/api/?index=${index}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                $('#loader').hide();
                let options = json.message.map(generateRankingTable);
                $("#advRanking tbody").append(options);
            });
        });
    }

    function generateRankingManagers() {
        $('#loader').show();
        fetch(`<?= BASEURL ?>dashboard/transations/managers/api/?index=${index}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                $('#loader').hide();
                let options = json.message.map(generateRankingTable);
                $("#managersTable tbody").append(options);
            });
        });
    }

    function generateRankingManagersGroup() {
        $('#loader').show();
        fetch(`<?= BASEURL ?>dashboard/transations/managers/group/api/?index=${index}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                $('#loader').hide();
                let options = json.message.map(generateRankingTable);
                $("#managersGroupTable tbody").append(options);
            });
        });
    }


    function generateTasks() {
        $('#loader').show();
        fetch(`<?= BASEURL ?>dashboard/tasks/api/?index=${index}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                $('#loader').hide();
                let options = json.message.map(generateTasksCard);
                $("#tasksDiv").append(options);
            });
        });
    }

    function dashboardData() {
        generateRankingAdvisors();
        generateRankingManagersGroup();
        generateRankingManagers();
        generateMessages();
        generateTasks();
    }

    $(document).ready(function () {
        dashboardData();
    });

    function taskStatus(id) {
        fetch(`<?= BASEURL ?>dashboard/tasks/status/${id}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        });
        document.getElementById(`cardTask${id}`).classList.add("d-none");
    }

    function maskMoneyTable(value) {
        var money = parseFloat(value);

        money = money.toLocaleString('en-us', {style: 'currency', currency: 'USD'});

        return money;
    }

</script>