<div class="row">
    <div class="col">
        <div class="card p-3">
            <div class="row">
                <div class="col">
                    <h5 class="title">Approved Transactions</h5>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <ul class="nav nav-tabs nav-justified">
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#managers">Managers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#menu1">Managers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#advisors">Advisors</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="card-body">
                <div class="tab-content">
                    <div class="tab-pane container active" id="advisors">
                        <div class="row" id="advisors">
                            <div class="col">
                                <table class="table table-sm table-hover" id="rankingAdvisor">
                                    <thead>
                                    <tr>
                                        <th scope="col" class="text-center">#</th>
                                        <th scope="col" class="text-center">User</th>
                                        <th scope="col" class="text-center">Country</th>
                                        <th scope="col" class="text-center">New Accounts</th>
                                        <th scope="col" class="text-center">WITHDRAWALS</th>
                                        <th class="text-center">NEW DEPOSITS</th>
                                        <th class="text-center">NET MARGIN IN</th>
                                    </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane container" id="managers">
                        <div class="row"></div>
                    </div>
                    <div class="tab-pane container" id="advisors">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <?php if ($messages != null): ?>
        <div class="card p-3">
            <div class="row">
                <div class="col-md-8">
                    <h5 class="title">Messages</h5>
                </div>
            </div>
            <div class="card-body" id="messagesDiv">

            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="row">
    <div class="col">
        <?php if ($tasks != null): ?>
            <div class="card p-3">
                <div class="row">
                    <div class="col-md-8">
                        <h5 class="title">Tasks</h5>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row" id="tasksDiv"></div>

                </div>
            </div>
        <?php endif; ?>
    </div>
</div>

<script>

    var index = 0;

    function generateMessagesCard(message) {
        return `<div class="bg-white p-3 mb-4" style="border: solid 1px rgb(0, 0, 0, 0.25);">
                    <div class="col">
                        <div class="row">
                            <div class="col-md-11" data-toggle="collapse" data-target="#collapse${message.id}" aria-expanded="false" aria-controls="collapse${message.id}">
                                <h6 class="my-auto">
                                      ${message.title}
                                </h6>
                            </div>
                            <div class="col-md-1 text-right">
                                <a><i class="fa fa-check-circle" id="iconCheck"></i></a>
                            </div>
                        </div>
                        <div class="row mt-2">
                                <div class="col" style="font-size: 12px">
                                    <i class="fa fa-calendar"></i> ${message.date}
                                    <i class="fa fa-clock-o ml-2"></i> ${message.time}
                                    <i class="fa fa-user ml-2"></i> ${message.user}
                                </div>
                            </div>
                        <div class="row">
                            <div id="collapse${message.id}" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                              <div class="card-body text-justify">
                                ${message.description}
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
        `;
    }

    function generateMessages() {
        $('#loader').show();
        fetch(`<?= BASEURL ?>dashboard/messages/api/?index=${index}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                $('#loader').hide();
                let options = json.message.map(generateMessagesCard);
                $("#messagesDiv").append(options);
            });
        });

    }

    function generateTasksCard(task) {
        let time = '';
        if (task.time != null) time = `${task.time}:`;
        return `<div class="col-md-4 my-2" id="cardTask${task.id}">
                    <div class="row bg-white p-3 card-task">
                        <div class="col-md-4 my-auto">
                            ${actionIcon(task.type)}
                        </div>
                        <div class="col-md-8 card-date">
                            <div class="row">
                                <div class="col"> <b>${time} ${actionStr(task.type)}</b></div>
                            </div>
                            <div class="row">
                                <div class="col"> ${task.deal}</div>
                            </div>
                            <div class="row">
                                <div class="col-md-9"></div>
                                <div class="col-md-3 text-right" onclick="taskStatus(${task.id})"><a><i class="fa fa-check-circle" id="iconCheck"></i></a></div>
                            </div>
                        </div>
                    </div>
                </div>`;
    }

    function actionStr(action) {
        switch (parseInt(action)) {
            case 2:
                return 'Call';
            case 3:
                return 'Meeting';
            case 4:
                return 'Email';
            case 5:
                return 'Lunch';
            case 6:
                return 'Task';
            default:
                return 'Unknown';

        }
    }

    function actionIcon(action) {
        switch (parseInt(action)) {
            case 2:
                return `<i class="fa fa-3x fa-phone text-gray"></i>`;
            case 3:
                return `<i class="fa fa-3x fa-users text-gray"></i>`;
            case 4:
                return `<i class="fa fa-3x fa-paper-plane text-gray"></i>`;
            case 5:
                return `<i class="fa fa-3x fa-utensils text-gray"></i>`;
            case 6:
                return `<i class="fa fa-3x fa-clock text-gray"></i>`;
            default:
                return `<i class="fa fa-3x fa-phone text-gray"></i>`;
        }
    }

    function generateRankingAdvisorsTable(transaction) {

        return `<tr>
                    <td class="text-center"></td>
                    <td class="text-center">${transaction.user}</td>
                    <td class="text-center">${transaction.country}</td>
                    <td class="text-center">${transaction.accounts}</td>
                    <td class="text-center"></td>
                    <td class="text-center"></td>
                    <td class="text-center">${maskMoneyTable(transaction.totalCapture)}</td>
                </tr>
        `;
    }

    function generateRankingAdvisors() {
        $('#loader').show();
        fetch(`<?= BASEURL ?>dashboard/transations/advisors/api/?index=${index}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                $('#loader').hide();
                let options = json.message.map(generateRankingAdvisorsTable);
                $("#rankingAdvisor tbody").append(options);
            });
        });
    }

    function generateTasks() {
        $('#loader').show();
        fetch(`<?= BASEURL ?>dashboard/tasks/api/?index=${index}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                $('#loader').hide();
                let options = json.message.map(generateTasksCard);
                $("#tasksDiv").append(options);
            });
        });
    }

    function dashboardData() {
        generateRankingAdvisors();
        generateMessages();
        generateTasks();
    }

    $(document).ready(function () {
        dashboardData();
    });

    function taskStatus(id) {
        fetch(`<?= BASEURL ?>dashboard/tasks/status/${id}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        });
        document.getElementById(`cardTask${id}`).classList.add("d-none");
    }

    function maskMoneyTable(value) {
        var money = parseFloat(value);

        money = money.toLocaleString('en-us', {style: 'currency', currency: 'USD'});

        return money;
    }

</script>