<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-4">
                        <h5 class="title">Projetos</h5>
                    </div>
                    <div class="col-md-8 ">
                        <a class="btn btn-primary float-right" href="<?= BASEURL ?>projetos/cadastro"><i
                                    class="fa fa-plus"></i> Projeto
                        </a>
                    </div>
                </div>
                <form id="filter">
                    <div class="row">
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="dateFilter">Dê</label>
                                <input class="form-control" id="dateFilter" name="start" type="text"
                                       placeholder="dd/mm/AAAA" data-mask="99/99/9999">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="dateFilter">Até</label>
                                <input class="form-control" id="dateFilter" name="end" type="text"
                                       placeholder="dd/mm/AAAA" data-mask="99/99/9999">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="typeFilter">Tipo</label>
                                <select class="form-control" id="typeFilter" name="type">
                                    <option value="0">Selecione</option>
                                    <?php foreach ($typeOfProject as $service): ?>
                                        <option value="<?= $service->getId() ?>" ><?= $service->getName() ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="responsibleFilter">Responsável</label>
                                <select class="form-control" id="responsibleFilter" name="responsible">
                                    <option value="0">Selecione</option>
                                    <?php foreach ($users as $user): ?>
                                        <option value="<?= $user->getId() ?>"><?= $user->getName() ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="statusFilter">Status</label>
                                <select class="form-control" id="statusFilter" name="status">
                                    <option value="0">Selecione</option>
                                    <option value="1">Tramitando</option>
                                    <option value="2">Arquivado</option>
                                    <option value="3">Aprovado</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col text-right">
                            <button class="btn btn-warning" onclick="pdf()" type="reset" ><i class="fa fa-file-pdf-o"></i></button>
                            <button class="btn btn-success" onclick="csv()" type="reset" ><i class="fa fa-file-excel-o"></i></button>
                            <button class="btn btn-danger" type="reset" onclick="resetTable()">Limpar</button>
                            <button class="btn btn-primary" type="submit">Filtrar</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-body">
                <p>Exibindo <span id="partial"></span> de <span id="total"></span> </p>
                <table id="projectsTable" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th class="text-center">Data</th>
                        <th class="text-center">Tipo</th>
                        <th class="text-center">Assunto</th>
                        <th class="text-center">Responsável</th>
                        <th class="text-center">Anexos</th>
                        <th class="text-center">Status</th>
                        <th class="text-center">Açoes</th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>

    var index = 0;
    var partial = 0;
    var total = 1;
    var start = 0;
    var end = 0;
    var type = 0;
    var responsible = 0;
    var status = 0;

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        start = formData.start;
        end = formData.end;
        type = formData.type;
        responsible = formData.responsible;
        status = formData.status;
        $("#projectsTable tbody").empty();
        generateTable();
    })

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        start = 0;
        end = 0;
        type = 0;
        responsible = 0;
        status = 0;
        $("#projectsTable tbody").empty();
        generateTable();
    }

    function projectView(id) {
        return `<?= BASEURL ?>projetos/visualizar/${id}`;
    }

    function projectEdit(id) {
        return `<?= BASEURL ?>projetos/cadastro/${id}`;
    }

    function statusStr(status) {
        switch (parseInt(status)) {
            case 1:
                return 'Tramitando';
            case 2:
                return 'Arquivado';
            case 3:
                return 'Aprovado';
            default:
                return 'Desconhecido';
        }
    }

    function formatAttachment(project) {

        return `<?= BASEURL ?>uploads/projetos/${project}`;
    }

    function generateProjectsTable(projects) {
        if (projects.projectFile != null){
            projectFile = ` <a class="btn btn-sm btn-primary" href="${formatAttachment(projects.projectFile)}" target="_blank">Anexo</a> `;
        } else {projectFile = ''}
        let actions = '';
        actions += `<a href="${projectView(projects.id)}"><i class="fa fa-search text-info" title="Visualizar"></i></a>
                    <a href="${projectEdit(projects.id)}"><i class="fa fa-pencil text-info" title="Editar"></i></a>`;
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td class="text-center">${projects.date}</td>
                    <td class="text-center">${projects.name}</td>
                    <td class="text-center">${projects.subjectMatter}</td>
                    <td class="text-center">${projects.user}</td>
                    <td class="text-center">${projectFile}</td>
                    <td class="text-center">${projects.status}</td>
                    ${actions}
                </tr>`;
    }


    function generateTable() {
        if (total > partial) {
            $('#loader').show();
            fetch(`<?= BASEURL ?>api/projetos/?index=${index}&type=${type}&status=${status}&responsible=${responsible}&start=${start}&end=${end}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#loader').hide();
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    let options = json.message.map(generateProjectsTable);
                    $("#projectsTable tbody").append(options);
                });
            });
        }
    }

    function pdf() {
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        start = formData.start;
        end = formData.end;
        type = formData.type;
        responsible = formData.responsible;
        status = formData.status;
        window.open(`<?= BASEURL ?>projetos/pdf/?index=${index}&type=${type}&status=${status}&responsible=${responsible}&start=${start}&end=${end}`, '_blank');
    }

    function csv() {
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        start = formData.start;
        end = formData.end;
        type = formData.type;
        responsible = formData.responsible;
        status = formData.status;
        window.open(`<?= BASEURL ?>projetos/csv/?index=${index}&type=${type}&status=${status}&responsible=${responsible}&start=${start}&end=${end}`, '_blank');
    }


    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });

</script>