<div class="card">
    <div class="row mt-4">
        <div class="col">
            <h5 class="title">Cadastro de Novo Projeto</h5>
        </div>
    </div>

    <form id="form">
        <input type="hidden" name="id" value="<?= $projects ? $projects->getId() : 0 ?>" >
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <label for="type">Tipo</label>
                    <select id="type" name="type" class="form-control" >
                        <option value="0">Selecione</option>
                        <?php foreach ($typeOfProject as $service): ?>
                            <option value="<?= $service->getId() ?>" <?= $projects && $projects->getType()->getId() == $service->getId() ? 'selected' : ''?> >
                                <?= $service->getName() ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="col-md-9">
                <div class="form-group">
                    <label for="subjectMatter">Assunto</label>
                    <input id="subjectMatter" placeholder="Assunto" name="subjectMatter" type="text"
                           class="form-control" value="<?= $projects ? $projects->getSubjectMatter() : '' ?>" >
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label for="number">Número</label>
                    <input id="number" placeholder="Número" name="number"
                           type="text" class="form-control" value="<?= $projects ? $projects->getNumber() : '' ?>"  >
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="status">Status</label>
                    <select id="status" name="status" class="form-control" >
                        <option value="0" >Selecione</option>
                        <option value="1" <?= $projects && $projects->getStatus() == 1 ? 'selected' : ''?>>Tramitando</option>
                        <option value="2" <?= $projects && $projects->getStatus() == 2 ? 'selected' : ''?>>Arquivado</option>
                        <option value="3" <?= $projects && $projects->getStatus() == 3 ? 'selected' : ''?>>Aprovado</option>
                    </select>
                </div>
            </div>
            <div class="col-md-4 mt-2">
                <div class="form-group">
                    <span class="fileselector">
                        <label class="btn btn-block btn-danger text-white" style="margin-top: 5px" for="projectFile">
                            <input class="upload-file-selector" id="projectFile" type="file"
                                   name="projectFile">
                            <i class="fa fa-paperclip margin-correction"></i>
                                <span id="projectFileLabel" default="Anexar Arquivo">Anexar Arquivo</span>
                        </label>
                    </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="link">Link</label>
                    <input id="link" placeholder="Link" name="link"
                              type="text" class="form-control" value="<?= $projects ? $projects->getLink() : '' ?>" >
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="description">Descrição</label>
                    <textarea id="description" placeholder="Adicione uma Descrição" name="description"
                              type="text" class="w-100" rows="10" ><?= $projects ? $projects->getDescription() : '' ?></textarea>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col text-right">
                <button type="submit" id="save" class="btn btn-success">Confirmar</button>
            </div>
        </div>
    </form>
    <div class="row">
        <div class="col">
            <div style="display: none" id="messageForm" class="alert" role="alert"></div>
        </div>
    </div>
</div>

<script>

    const formAdd = document.getElementById('form');
    const divMessageForm = document.getElementById('messageForm');

    formAdd.addEventListener('submit', e => {
        $('#save').addClass('disabled');
        e.preventDefault();
        showLoading();
        let method = 'POST';
        let formData = formDataToJson('form');
        fetch("<?= BASEURL ?>projetos/cadastro", {
            method: method,
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
            },
            body: new FormData(formAdd)
        }).then(response => {
            closeLoading();
            divMessageForm.classList.add("alert-danger");
            divMessageForm.classList.remove("alert-success");
            $('#save').removeClass('disabled');
            response.json().then(json => {
                divMessageForm.textContent = json.message;
                divMessageForm.style.display = 'block';
                if (response.status === 201) {
                    divMessageForm.classList.add("alert-success");
                    divMessageForm.classList.remove("alert-danger");
                    formAdd.reset();
                    setTimeout(function () {
                        window.location.href = "<?= BASEURL ?>projetos";
                    }, 2000);
                }
            });
        });
    });

    $(document).ready(function () {
        $('input:file').change(function (e) {
            let input = e.target;

            if (input.files.length > 0) {
                input.parentElement.classList.remove('btn-primary');
                input.parentElement.classList.remove('btn-danger');
                input.parentElement.classList.add('btn-success');
                input.text = input.value;
                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = input.value;
            } else {
                input.parentElement.classList.remove('btn-success');
                input.parentElement.classList.add('btn-danger');
                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = document.getElementById(labelId).getAttribute('default');
            }
        });
    });
</script>