<div class="card">
    <div class="card-header">
        <div class="col">
            <h5 class="title">Visualizar Projeto</h5>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <b>Tipo de Projeto: </b> <?= $projects->getType()->getName() ?>
            </div>
            <div class="col-md-8">
                <b>Data: </b> <?= $projects->getDate()->format('d/m/Y') ?>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col">
                <b>Assunto: </b> <?= $projects->getSubjectMatter() ?>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col">
                <b>Status: </b> <?= $projects->getStatusStr() ?>
            </div>
        </div>
        <?php if ($projects->getLink() != ''): ?>
            <div class="row mt-3">
                <div class="col">
                    <b>Link: </b> <a href="<?= $projects->getLink() ?>" target="_blank"><?= $projects->getLink() ?></a>
                </div>
            </div>
        <?php endif; ?>
        <div class="row mt-3">
            <div class="col">
                <b>Descrição: </b> <?= $projects->getDescription() ?>
            </div>
        </div>
    </div>
</div>