<div class="row">
    <div class="col">
        <div class="card p-3">
            <form id="filter">
                <div class="row">
                    <div class="col-md-2">
                        <a class="btn btn-primary text-white" href="#" onclick="openModal()"><i
                                    class="fa fa-plus"></i> Transaction</a>
                    </div>
                    <div class="col-md-3 my-auto">
                        <div class="form-group mt-2">
                            <select class="form-control" id="userFilter" name="user" type="text">
                                <option value="0">Select User</option>
                                <?php foreach ($users as $us): ?>
                                    <option value="<?= $us->getId() ?>"><?= $us->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-4 my-auto">
                        <div class="form-group mt-2">
                            <select class="form-control" id="countryFilter" name="country" type="text">
                                <option value="0">Select Country</option>
                                <?php foreach ($countries as $country): ?>
                                    <option value="<?= $country->getId() ?>"><?= $country->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3 text-right">
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Cancel</button>
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card p-3">
            <p>Showing <span id="partial"></span> of <span id="total"></span></p>
            <div class="table-responsive-sm">
                <table class="table table-sm table-hover table-bordered" id="transactionsTable" width="100%"
                       cellspacing="0">
                    <thead>
                    <tr>
                        <th class="text-center">Date</th>
                        <th class="text-center">User</th>
                        <th class="text-center">Country</th>
                        <th class="text-center">New Deposits</th>
                        <th class="text-center">Withdrawals</th>
                        <th class="text-center">Resposible</th>
                        <th class="text-center">Actions</th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Modal Cadastro-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Transaction registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addTransaction" method="post">
                <div class="form-group">
                    <input type="hidden" name="transactionId" id="transactionId">
                    <div class="row">
                        <div class="col">
                            <label for="userTransaction">User</label>
                            <select id="userTransaction" name="user" class="form-control">
                                <option value="0">Select User</option>
                                <?php foreach ($users as $us): ?>
                                    <option value="<?= $us->getId() ?>"><?= $us->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="depositTransaction">Deposit</label>
                            <input class="form-control" id="depositTransaction" name="deposit" placeholder="Deposit">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="withdrawalsTransaction">Withdrawals</label>
                            <input class="form-control" id="withdrawalsTransaction" name="withdrawals"
                                   placeholder="Withdrawals">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save Transaction</button>
                    </div>
                </div>
                <div style="display: none" id="transaction" class="alert alert-danger" role="alert"></div>
            </form>
        </div>
    </div>
</div>
<script src="<?= BASEURL ?>assets/js/jquery.maskMoney.min.js"></script>
<script>

    var index = 0;
    var partial = 0;
    var total = 1;
    var user = 0;
    var country = 0;

    function openModal() {
        $('#modal').modal('show');
        $('#transaction').hide();
        document.getElementById('addTransaction').reset();
        $("#withdrawalsTransaction").maskMoney({
            prefix: '$ ',
            allowNegative: true,
            thousands: '.',
            decimal: ',',
            affixesStay: false
        });
        $("#depositTransaction").maskMoney({
            prefix: '$ ',
            allowNegative: true,
            thousands: '.',
            decimal: ',',
            affixesStay: false
        });
    }

    const formAdd = document.getElementById('addTransaction');
    const divMessage = document.getElementById('transaction');

    formAdd.addEventListener('submit', e => {
        var teste = document.getElementById('projectFile');
        console.log(teste);
        e.preventDefault();
        showLoading();
        let method = 'POST';
        let formData = formDataToJson('addTransaction');
        fetch("<?= BASEURL ?>transactions/register", {
            method: method,
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
            },
            body: new FormData(formAdd)
        }).then(response => {
            closeLoading();
            divMessage.classList.add("alert-danger");
            divMessage.classList.remove("alert-success");
            $('#save').removeClass('disabled');
            response.json().then(json => {
                divMessage.textContent = json.message;
                divMessage.style.display = 'block';
                if (response.status === 201) {
                    divMessage.classList.add("alert-success");
                    divMessage.classList.remove("alert-danger");
                    formAdd.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        user = formData.user;
        country = formData.country;
        $("#transactionsTable tbody").empty();
        generateTable();
    });

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        user = 0;
        country = 0;
        $("#transactionsTable tbody").empty();
        generateTable();
    }


    function generateTransactionsTable(transaction) {
        let deposit = '';
        if (transaction.deposit != 0) deposit = maskMoneyTable(transaction.deposit);
        let withdrawals = '';
        if (transaction.withdrawals != 0) withdrawals = maskMoneyTable(transaction.withdrawals);
        let actions = '';
        actions += `<i class="fa fa-times text-danger ml-2" title="Delete" onclick="deleteTransaction(${transaction.id})"></i> `;
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td class="text-center">${transaction.date}</td>
                    <td class="text-center">${transaction.user}</td>
                    <td class="text-center">${transaction.country}</td>
                    <td class="text-center">${deposit}</td>
                    <td class="text-center">${withdrawals}</td>
                    <td class="text-center">${transaction.responsible}</td>
                    ${actions}
                </tr>`;
    }

    function deleteTransaction(id) {
        $('#loader').show();
        fetch(`<?= BASEURL ?>api/transactions/delete/${id}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        });
        location.reload();
    }

    function generateTable() {
        if (total > partial) {
            $('#loader').show();
            fetch(`<?= BASEURL ?>api/transactions/?index=${index}&user=${user}&country=${country}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#loader').hide();
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    let options = json.message.map(generateTransactionsTable);
                    $("#transactionsTable tbody").append(options);

                });
            });
        }
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });

    function maskMoneyTable(value) {
        var money = parseFloat(value);

        money = money.toLocaleString('en-us', {style: 'currency', currency: 'USD'});

        return money;
    }
</script>
