<div class="row">
    <div class="col">
        <div class="card p-3">
            <form id="filter">
                <div class="row">
                    <div class="col-md-2">
                            <a class="btn btn-primary text-white" href="#" onclick="openModal()"><i
                                        class="fa fa-plus"></i> Lead</a>
                    </div>
                    <div class="col-md-4 my-auto">
                        <div class="form-group mt-2">
                            <input class="form-control" id="nameFilter" name="name" type="text" placeholder="Name">
                        </div>
                    </div>
                    <div class="col-md-3 my-auto">
                        <div class="form-group mt-2">
                            <select class="form-control" id="countryFilter" name="country" type="text">
                                <option value="0">Select Country</option>
                                <?php foreach ($countries as $country): ?>
                                <option value="<?= $country->getId() ?>>"><?= $country->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3 text-right">
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Cancel</button>
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="card p-3">
            <p>Showing <span id="partial"></span> of <span id="total"></span></p>
            <table class="table table-bordered table-striped" id="leadsTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th class="text-center">Name</th>
                    <th class="text-center">Email</th>
                    <th class="text-center">Phone</th>
                    <th class="text-center">Owner</th>
                    <th class="text-center">Country</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>


<!-- Modal Cadastro-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Lead Registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addLead" method="post">
                <div class="form-group">
                    <input type="hidden" name="leadId" id="leadId">
                    <div class="row">
                        <div class="col">
                            <label for="name">Name</label>
                            <input id="name" name="name" class="form-control" type="text" placeholder="Name">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="email">Email</label>
                            <input id="email" name="email" class="form-control" type="email" placeholder="Email">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="phone">Phone</label>
                            <input id="phone" name="phone" class="form-control" type="text" placeholder="Phone">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="country">Country</label>
                            <select class="form-control" id="country" name="country" type="text">
                                <option value="0">Select Country</option>
                                <?php foreach ($countries as $country): ?>
                                    <option value="<?= $country->getId() ?>>"><?= $country->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save Lead</button>
                    </div>
                </div>
                <div style="display: none" id="message" class="alert alert-danger" role="alert"></div>
            </form>
        </div>
    </div>
</div>

<script>

    var index = 0;
    var partial = 0;
    var total = 1;
    var country = 0;
    var name = 0;

    function openModal() {
        $('#modal').modal('show');
        $('#message').hide();
        document.getElementById('addLead').reset();
    }

    function openModalEdit(id) {

        document.getElementById('addLead').reset();
        document.getElementById('leadId').value = id;
        $('#modal').modal('show');
        $('#message').hide();
        if (id > 0) {
            showLoading();
            fetch(`<?= BASEURL ?>leads/api/${id}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    json = json.message[0];
                    closeLoading();
                    document.getElementById('email').value = json.email;
                    document.getElementById('name').value = json.name;
                    document.getElementById('country').value = json.country;
                });
            });
        }
    }

    const formAdd = document.getElementById('addLead');
    const divMessage = document.getElementById('message');

    formAdd.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let formData = formDataToJson('addLead');
        fetch("<?= BASEURL ?>leads/register", {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            closeLoading();
            divMessage.classList.add("alert-danger");
            divMessage.classList.remove("alert-success");
            response.json().then(json => {
                divMessage.textContent = json.message;
                divMessage.style.display = 'block';
                if (response.status === 201) {
                    $('#modal').modal('hide');
                    divMessage.classList.add("alert-success");
                    divMessage.classList.remove("alert-danger");
                    formAdd.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        name = formData.name;
        country = formData.country;
        $("#leadsTable tbody").empty();
        generateTable();
    });

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        name = 0;
        country = 0;
        $("#leadsTable tbody").empty();
        generateTable();
    }

    function generateLeadsTable(user) {
        let actions = '';
        actions += `<i class="fa fa-pencil text-info" title="Edit" onclick="openModalEdit(${user.id})"></i> `;
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td class="text-center">${user.name}</td>
                    <td class="text-center">${typeStr(user.type)}</td>
                    <td class="text-center">${user.email}</td>
                    <td class="text-center">${activeStr(user.active)}</td>
                    ${actions}
                </tr>`;
    }

    function typeStr(type) {
        if (type == 1) {
            return 'Admin';
        } else if (type == 2) {
            return 'Manager';
        } else if (type == 3) {
            return 'Advisor';
        }
    }

    function activeStr(active) {
        if (active == 1) {
            return 'Active';
        } else {
            return 'Inactive';
        }
    }

    function generateTable() {
        if (total > partial) {
            $('#loader').show();
            fetch(`<?= BASEURL ?>leads/api/?index=${index}&name=${name}&country=${country}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#loader').hide();
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    let options = json.message.map(generateLeadsTable);
                    $("#leadsTable tbody").append(options);
                });
            });
        }
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });

</script>
