<div class="row">
    <div class="col">
        <div class="card p-3">
            <form id="filter">
                <div class="row">
                    <div class="col-md-2">
                        <a class="btn btn-primary text-white" href="#" onclick="openModal()"><i
                                    class="fa fa-plus"></i> Lead</a>
                    </div>
                    <div class="col-md-4 my-auto">
                        <div class="form-group mt-2">
                            <input class="form-control" id="nameFilter" name="name" type="text" placeholder="Name">
                        </div>
                    </div>
                    <div class="col-md-3 my-auto">
                        <div class="form-group mt-2">
                            <select class="form-control" id="countryFilter" name="country" type="text">
                                <option value="0">Select Country</option>
                                <?php foreach ($countries as $country): ?>
                                    <option value="<?= $country->getId() ?>"><?= $country->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3 text-right">
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Cancel</button>
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="card p-3">
            <p>Showing <span id="partial"></span> of <span id="total"></span></p>
            <div class="table-responsive-sm">
                <table class="table table-sm table-hover table-bordered" id="leadsTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th class="text-center">Name</th>
                        <th class="text-center">Email</th>
                        <th class="text-center">Phone</th>
                        <th class="text-center">Owner</th>
                        <th class="text-center">Country</th>
                        <th class="text-center">Actions</th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Modal Cadastro-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Lead Registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addLead" method="post">
                <div class="form-group">
                    <input type="hidden" name="leadId" id="leadId">
                    <div class="row">
                        <div class="col">
                            <label for="nameLead">Name</label>
                            <input id="nameLead" name="nameLead" class="form-control" type="text" placeholder="Name">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="emailLead">Email</label>
                            <input id="emailLead" name="emailLead" class="form-control" type="email"
                                   placeholder="Email">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="phoneLead">Phone</label>
                            <input id="phoneLead" name="phoneLead" class="form-control" type="text" placeholder="Phone">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="countryLead">Country</label>
                            <select class="form-control" id="countryLead" name="countryLead" type="text">
                                <option value="0">Select Country</option>
                                <?php foreach ($countries as $country): ?>
                                    <option value="<?= $country->getId() ?>>"><?= $country->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save Lead</button>
                    </div>
                </div>
                <div style="display: none" id="message" class="alert alert-danger" role="alert"></div>
            </form>
        </div>
    </div>
</div>

<!-- Modal To Deal-->
<div class="modal fade" id="modalToDeal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Convert to Deal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addDeal" method="post">
                <div class="form-group">
                    <input type="hidden" name="dealId" id="dealToId">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="nameDeal">Name</label>
                            <input id="nameDeal" name="name" class="form-control" type="text" placeholder="Name">
                        </div>
                        <div class="col-md-6">
                            <label for="companyDeal">Company</label>
                            <input id="companyDeal" name="company" class="form-control" type="text"
                                   placeholder="Company">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="emailDeal">Email</label>
                            <input id="emailDeal" name="email" class="form-control" type="email" placeholder="Email">
                        </div>
                        <div class="col-md-6">
                            <label for="countryDeal">Country</label>
                            <select class="form-control" id="countryDeal" name="country" type="text">
                                <option value="0">Select Country</option>
                                <?php foreach ($countries as $country): ?>
                                    <option value="<?= $country->getId() ?>"><?= $country->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="phoneDeal">Phone</label>
                            <input id="phoneDeal" name="phone" class="form-control" type="text"
                                   placeholder="+99 99 9999-9999">
                        </div>
                        <div class="col-md-4">
                            <label for="statusDeal">Status</label>
                            <select id="statusDeal" name="status" class="form-control">
                                <option value="0">Select</option>
                                <option value="1">Follow Up</option>
                                <option value="2">Pending Agreement</option>
                                <option value="3">Approved Terms</option>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label for="officeDeal">Office</label>
                            <input id="officeDeal" name="office" class="form-control" type="text" placeholder="Office">
                        </div>
                        <input type="hidden" value="0" name="type" id="type">
                        <input type="hidden" value="Deal created" name="activityDeal" id="activityDeal">
                        <input type="hidden" value="1" name="typeDeal" id="typeDeal">
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save Deal</button>
                    </div>
                </div>
                <div style="display: none" id="messageDeal" class="alert alert-danger" role="alert"></div>
            </form>
        </div>
    </div>
</div>

<script>

    var index = 0;
    var partial = 0;
    var total = 1;
    var country = 0;
    var name = 0;
    var activity = 0;

    function openModal() {
        $('#modal').modal('show');
        $('#message').hide();
        document.getElementById('addLead').reset();
    }

    const formAdd = document.getElementById('addLead');
    const divMessage = document.getElementById('message');

    formAdd.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let formData = formDataToJson('addLead');
        fetch("<?= BASEURL ?>leads/register", {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            closeLoading();
            divMessage.classList.add("alert-danger");
            divMessage.classList.remove("alert-success");
            response.json().then(json => {
                divMessage.textContent = json.message;
                divMessage.style.display = 'block';
                if (response.status === 201) {
                    $('#modal').modal('hide');
                    divMessage.classList.add("alert-success");
                    divMessage.classList.remove("alert-danger");
                    formAdd.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    const formAddDeal = document.getElementById('addDeal');
    const divMessageDeal = document.getElementById('messageDeal');

    formAddDeal.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let formData = formDataToJson('addDeal');
        fetch("<?= BASEURL ?>deals/register", {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            closeLoading();
            divMessageDeal.classList.add("alert-danger");
            divMessageDeal.classList.remove("alert-success");
            response.json().then(json => {
                divMessageDeal.textContent = json.message;
                divMessageDeal.style.display = 'block';
                if (response.status === 201) {
                    $('#modalToDeal').modal('hide');
                    divMessageDeal.classList.add("alert-success");
                    divMessageDeal.classList.remove("alert-danger");
                    formAddDeal.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        name = formData.name;
        country = formData.country;
        $("#leadsTable tbody").empty();
        generateTable();
    });

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        name = 0;
        country = 0;
        $("#leadsTable tbody").empty();
        generateTable();
    }

    function generateLeadsTable(lead) {
        let actions = '';
        actions += `<a class="btn btn-primary text-white" onclick="openModalToDeal(${lead.id})">To Deal</a>`;
        actions += `<i class="fa fa-times text-danger ml-2" title="Delete" onclick="deleteLead(${lead.id})"></i> `;
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td class="text-center">${lead.name}</td>
                    <td class="text-center">${lead.email}</td>
                    <td class="text-center">${lead.phone}</td>
                    <td class="text-center">${lead.user}</td>
                    <td class="text-center">${lead.country}</td>
                    ${actions}
                </tr>`;
    }

    function openModalToDeal(id) {
        $('#modalToDeal').modal('show');
        $('#message').hide();
        if (id > 0) {
            showLoading();
            fetch(`<?= BASEURL ?>api/leads/${id}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    json = json.message[0];
                    closeLoading();
                    console.log(json.phone);
                    console.log(json.email);
                    console.log(json.country);
                    console.log(json.name);
                    console.log(json.id);

                    document.getElementById('phoneDeal').value = json.phone;
                    document.getElementById('emailDeal').value = json.email;
                    document.getElementById('countryDeal').value = json.country;
                    document.getElementById('nameDeal').value = json.name;
                    document.getElementById('dealToId').value = json.id;
                });
            });
        }
    }

    function deleteLead(id) {
        var result = confirm('Are you sure about that?\nYour action will be permanent and you will not be able to recover the deleted data!');
        if (result == true) {
            $('#loader').show();
            fetch(`<?= BASEURL ?>api/leads/delete/${id}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            });
            location.reload();
        } else {
            return false;
        }
    }

    function generateTable() {
        if (total > partial) {
            $('#loader').show();
            fetch(`<?= BASEURL ?>api/leads/?index=${index}&name=${name}&country=${country}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#loader').hide();
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    let options = json.message.map(generateLeadsTable);
                    $("#leadsTable tbody").append(options);
                });
            });
        }
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });
</script>
