<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-4">
                        <h5 class="title">Reuniões</h5>
                    </div>
                    <div class="col-md-8 ">
                        <a class="btn btn-primary float-right" href="<?= BASEURL ?>eventos/cadastro"><i
                            class="fa fa-plus"></i> Eventos
                        </a>
                    </div>
                </div>
                <form id="filter">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="dateFilter">Data</label>
                                <input class="form-control" id="dateFilter" name="start" type="text" placeholder="dd/mm/AAAA" data-mask="99/99/9999">
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                <label for="adressFilter">Endereço</label>
                                <input class="form-control" id="adressFilter" name="adress" type="text" placeholder="Endereço">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="themeFilter">Pauta</label>
                                <input class="form-control" id="themeFilter" name="theme" type="text" placeholder="Pauta">
                            </div>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col text-right">
                            <button class="btn btn-danger" type="reset" onclick="resetTable()">Limpar</button>
                            <button class="btn btn-primary" type="submit">Filtrar</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-body">
                <p>Exibindo <span id="partial"></span> de <span id="total"></span> </p>
                <table id="MeetingsTable" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th class="text-center">Data</th>
                        <th class="text-center">Endereço</th>
                        <th class="text-center">Pauta</th>
                        <th class="text-center">Açoes</th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>

    var index = 0;
    var partial = 0;
    var total = 1;
    var start = 0;
    var adress = 0;
    var theme = 0;

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        start = formData.start;
        adress = formData.adress;
        theme = formData.theme;
        $("#MeetingsTable tbody").empty();
        generateTable();
    })

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        start = 0;
        adress = 0;
        theme = 0;
        $("#MeetingsTable tbody").empty();
        generateTable();
    }

    function meetingView(id) {
        return `<?= BASEURL ?>eventos/visualizar/${id}`;
    }

    function meetingEdit(id) {
        return `<?= BASEURL ?>eventos/cadastro/${id}`;
    }

    function generateMeetingsTable(meetings) {
        let actions = '';
        actions += `<a href="${meetingView(meetings.id)}"><i class="fa fa-search text-info" title="Visualizar"></i></a>
                    <a href="${meetingEdit(meetings.id)}"><i class="fa fa-pencil text-info" title="Editar"></i></a>`;
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td class="text-center">${meetings.start}</td>
                    <td class="text-center">${meetings.adress}</td>
                    <td class="text-center">${meetings.theme}</td>
                    ${actions}
                </tr>`;
    }


    function generateTable() {
        if (total > partial) {
            $('#loader').show();
            fetch(`<?= BASEURL ?>api/reunioes/?index=${index}&start=${start}&adress=${adress}&theme=${theme}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#loader').hide();
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    let options = json.message.map(generateMeetingsTable);
                    $("#MeetingsTable tbody").append(options);
                });
            });
        }
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });

</script>