<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <h5 class="title">Detalhes da Reunião:</h5>
            </div>
            <div class="col-md-6 text-right">
                <button class="btn btn-warning" onclick="pdf()"><i class="fa fa-file-pdf-o"></i> Ata
                </button>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <b>Data e horário: </b> <?= $meetings->getStart()->format('d/m/Y H:i') ?>
            </div>
            <div class="col-md-8">
                <b>Local: </b> <?= $meetings->getAdressStr() ?>
            </div>
        </div>
        <div class="row mt-3">
            <?php if ($meetings->getContact()): ?>
            <div class="col-md-4">
                <b>Contato: </b> <?= $meetings->getContact() ?>
            </div>
            <?php endif; ?>
            <?php if ($meetings->getEmail()): ?>
            <div class="col-md-8">
                <b>E-mail: </b> <?= $meetings->getEmail() ?>
            </div>
            <?php endif; ?>
        </div>
        <div class="row mt-3">
            <div class="col">
                <b>Pauta: </b> <?= $meetings->getTheme() ?>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col">
                <b>Descrição: </b> <?= $meetings->getDescription() ?>
            </div>
        </div>
    </div>
</div>

<script>

    var id = <?= $meetings->getId() ?>;

    function pdf() {
        window.open(`<?= BASEURL ?>eventos/pdf/${id}`, '_blank');
    }

</script>