<div class="card">
    <div class="row mt-4">
        <div class="col">
            <h5 class="title">Cadastro de Novo Contato</h5>
        </div>
    </div>

    <form id="addContact">
        <input type="hidden" name="userId" id="userId" value="<?= $contacts ? $contacts->getId() : '' ?>">
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <label for="typeContact">Tipo de Contato</label>
                    <select id="typeContact" name="typeContact" class="form-control">
                        <option value="">Selecione</option>
                        <?php foreach ($typeContacts as $typeContact): ?>
                            <option value="<?= $typeContact->getId() ?>" <?= $contacts && $contacts->getTypeContact()->getId() == $typeContact->getId()? 'selected' : '' ?>
                            ><?= $typeContact->getName() ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="col-md-5">
                <div class="form-group">
                    <label for="name">Nome</label>
                    <input id="name" placeholder="Nome" name="name" value="<?= $contacts ? $contacts->getName() : '' ?>"
                           type="text" class="form-control">
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label for="phone">Telefone</label>
                    <input id="phone" placeholder="(__) ____-_____" value="<?= $contacts ? $contacts->getPhone() : '' ?>"
                           name="phone" data-mask="(99)9999-99999" type="text" class="form-control">
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label for="dateOfBirth">Data de Nascimento</label>
                    <input id="dateOfBirth" placeholder="dd/mm/AAAA" value="<?= $contacts ? $contacts->getDateOfBirth()->format('d/m/Y') : '' ?>"
                           name="dateOfBirth" data-mask="99/99/9999" type="text" class="form-control">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <label for="email">E-mail</label>
                    <input id="email" placeholder="E-mail" name="email" type="email" class="form-control"
                           value="<?= $contacts ? $contacts->getEmail() : '' ?>">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="zipCode">CEP</label>
                    <input class="form-control" name="zipCode" data-mask="99999-999"
                           type="text" id="zipCode" placeholder="Cep" value="<?= $contacts ? $contacts->getZipCode() : '' ?>"/>
                </div>
            </div>
            <div class="col-md-1">
                <div class="form-group">
                    <label for="ufId">Estado</label>
                    <input type="text" name="ufId" id="ufId" class="form-control" placeholder="UF" value="<?= $contacts ? $contacts->getUfId() : ''?>">
                    <input type="hidden" name="ufIdHidden" id="ufIdHidden">
                </div>
            </div>
            <div class="col-md-5">
                <div class="form-group">
                    <label for="cityId">Cidade</label>
                    <input type="text" name="cityId" id="cityId" class="form-control" placeholder="Cidade" value="<?= $contacts ? $contacts->getCityId() : '' ?>">
                    <input type="hidden" name="cityIdHidden" id="cityIdHidden">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="neighborhood">Bairro</label>
                    <input type="text" name="neighborhood" id="neighborhood" class="form-control" placeholder="Bairro"
                           value="<?= $contacts ? $contacts->getNeighborhood() : '' ?>">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="adress">Endereço</label>
                    <input type="text" name="adress" id="adress" class="form-control" placeholder="Endereço"
                           value="<?= $contacts ? $contacts->getAdress() : '' ?>">
                </div>
            </div>
        </div>
        <div class="row text-right">
            <div class="col text-right">
                <button type="submit" id="save" class="btn btn-success">Confirmar</button>
            </div>

        </div>
    </form>
    <div class="row">
        <div class="col">
            <div style="display: none" id="messageForm" class="alert" role="alert"></div>
        </div>
    </div>
</div>

<script>

    const formAdd = document.getElementById('addContact');
    const divMessage = document.getElementById('messageForm');

    formAdd.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let formData = formDataToJson('addContact');
        fetch("<?= BASEURL ?>contatos/cadastro", {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            closeLoading();
            divMessage.classList.add("alert-danger");
            divMessage.classList.remove("alert-success");
            response.json().then(json => {
                divMessage.textContent = json.message;
                divMessage.style.display = 'block';
                if (response.status === 201) {
                    $('#modal').modal('hide');
                    divMessage.classList.add("alert-success");
                    divMessage.classList.remove("alert-danger");
                    formAdd.reset();
                    setTimeout(function () {
                        window.location.href = "<?= BASEURL ?>contatos";
                    }, 2000);
                }
            });
        });
    });

    $(document).ready(function () {
        $("#zipCode").keyup(function () {
            loadAddress();
        });
    });

    function loadAddress() {
        var cep = $('#zipCode').val().replace(/\D/g, '');
        var validacep = /^[0-9]{8}$/;
        if (validacep.test(cep)) {
            $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados) {
                if (!("erro" in dados)) {
                    $("#uf").val(dados.uf);
                    $("#ufId").val(dados.uf);
                    $("#city").val(dados.localidade);
                    $("#cityIdHidden").val(dados.localidade);
                    $("#cityId").val(dados.localidade);
                    $("#ufIdHidden").val(dados.uf);
                }
            });
        }
    }
</script>