<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-4">
                        <h5 class="title">Contatos</h5>
                    </div>
                    <div class="col-md-8 ">
                        <a class="float-right btn btn-primary text-white" href="<?= BASEURL ?>contatos/cadastro"> Contato <i
                                    class="fa fa-plus"></i></a>
                    </div>
                </div>
                <form id="filter">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="nameFilter">Nome</label>
                                <input class="form-control" id="nameFilter" name="name" type="text" placeholder="Nome">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="emailFilter">E-mail</label>
                                <input class="form-control" id="emailFilter" name="email" type="text"
                                       placeholder="E-mail">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="typeContactFilter">Tipo de Contato</label>
                                <select id="typeContactFilter" name="typeContact" class="form-control">
                                    <option value="">Selecione</option>
                                    <?php foreach ($typeContacts as $typeContact): ?>
                                        <option value="<?= $typeContact->getId() ?>"><?= $typeContact->getName() ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col text-right">
                            <button class="btn btn-danger" type="reset" onclick="resetTable()">Limpar</button>
                            <button class="btn btn-primary" type="submit">Filtrar</button>
                        </div>
                    </div>
                </form>

            </div>
            <div class="card-body">
                <p>Exibindo <span id="partial"></span> de <span id="total"></span> </p>
                <table id="contactsTable" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th class="text-center">Nome</th>
                        <th class="text-center">E-mail</th>
                        <th class="text-center">Telefone</th>
                        <th class="text-center">Cidade</th>
                        <th class="text-center">Tipo</th>
                        <th class="text-center">Ações</th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                <div style="display: none" id="messageForm" class="alert" role="alert"></div>
            </div>
        </div>
    </div>
</div>
<script>

    var index = 0;
    var partial = 0;
    var total = 1;
    var email = 0;
    var name = 0;
    var type = 0;

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        email = formData.email;
        name = formData.name;
        type = formData.typeContact;
        $("#contactsTable tbody").empty();
        generateTable();
    });

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        email = 0;
        name = 0;
        type = 0;
        $("#contactsTable tbody").empty();
        generateTable();
    }

    function editContact(id) {
        return `<?= BASEURL ?>contatos/cadastro/${id}`;
    }

    function generateContactsTable(contacts) {
        let actions = '';
        actions += `<a href="${editContact(contacts.id)}"><i class="fa fa-pencil text-info" title="Editar"></i></a> `;
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td class="text-center">${contacts.name}</td>
                    <td class="text-center">${contacts.email}</td>
                    <td class="text-center">${contacts.phone}</td>
                    <td class="text-center">${contacts.cityId}</td>
                    <td class="text-center">${contacts.type}</td>
                    ${actions}
                </tr>`;
    }


    function generateTable() {
        if (total > partial) {
            $('#loader').show();
            fetch(`<?= BASEURL ?>api/contatos/?index=${index}&name=${name}&email=${email}&type=${type}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#loader').hide();
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    let options = json.message.map(generateContactsTable);
                    $("#contactsTable tbody").append(options);
                });
            });
        }
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });
</script>

