<div class="row">
    <div class="col">
        <div class="card p-3">
            <form id="filter">
                <div class="row">
                    <div class="col-md-2">
                            <a class="btn btn-primary text-white" href="#" onclick="openModal()"><i
                                        class="fa fa-plus"></i> Message</a>
                    </div>
                    <div class="col-md-7 my-auto">
                        <div class="form-group mt-2">
                            <input class="form-control" id="titleFilter" name="title" type="text" placeholder="Title">
                        </div>
                    </div>
                    <div class="col-md-3 text-right">
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Cancel</button>
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card p-3">
            <p>Showing <span id="partial"></span> of <span id="total"></span></p>
            <table class="table table-bordered table-striped" id="messagesTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th class="text-center">Description</th>
                    <th class="text-center">Status</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

<!-- Modal Cadastro-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Message registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addMessage" method="post">
                <div class="form-group">
                    <input type="hidden" name="messageId" id="messageId">
                    <div class="row">
                        <div class="col">
                            <label for="title">Title</label>
                            <input id="title" name="title" class="form-control" type="text" placeholder="Title">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="description">Description</label>
                            <textarea id="description" name="description" class="form-control" type="text"
                                      placeholder="Description"></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="active">Status</label>
                            <select id="active" name="active" class="form-control">
                                <option value="1">Active</option>
                                <option value="0">Inactive</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save Message</button>
                    </div>
                </div>
                <div style="display: none" id="message" class="alert alert-danger" role="alert"></div>
            </form>
        </div>
    </div>
</div>

<script src="<?= BASEURL ?>assets/js/plugins/tinymce/jquery.tinymce.min.js"></script>
<script src="<?= BASEURL ?>assets/js/plugins/tinymce/tinymce.min.js"></script>
<script>tinymce.init({
        selector: "textarea",
        menubar: false,
        statusbar: false,
        toolbar: 'styleselect | bold italic | fontsizeselect | alignleft aligncenter alignright alignjustify | bullist numlist | link image media | forecolor backcolor table',
        plugins: ["lists link image media textcolor table"],
        browser_spellcheck: true,
        imagetools_cors_hosts: ['www.tinymce.com', 'codepen.io'],
        setup: function (editor) {
            editor.on('change', function () {
                editor.save();
            });
        }
    });
</script>

<script>

    var index = 0;
    var partial = 0;
    var total = 1;
    var title = 0;
    var active = -1;

    function openModal() {
        $('#modal').modal('show');
        $('#message').hide();
        document.getElementById('addMessage').reset();
    }

    const formAdd = document.getElementById('addMessage');
    const divMessage = document.getElementById('message');

    formAdd.addEventListener('submit', e => {
        var teste = document.getElementById('projectFile');
        console.log(teste);
        e.preventDefault();
        showLoading();
        let method = 'POST';
        let formData = formDataToJson('addMessage');
        fetch("<?= BASEURL ?>messages/register", {
            method: method,
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
            },
            body: new FormData(formAdd)
        }).then(response => {
            closeLoading();
            divMessage.classList.add("alert-danger");
            divMessage.classList.remove("alert-success");
            $('#save').removeClass('disabled');
            response.json().then(json => {
                divMessage.textContent = json.message;
                divMessage.style.display = 'block';
                if (response.status === 201) {
                    divMessage.classList.add("alert-success");
                    divMessage.classList.remove("alert-danger");
                    formAdd.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        active = -1;
        title = formData.title;
        $("#messagesTable tbody").empty();
        generateTable();
    });

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        title = 0;
        active = -1;
        $("#messagesTable tbody").empty();
        generateTable();
    }


    function generateMessagesTable(message) {
        let actions = '';
        actions += `<i class="fa fa-pencil text-info" title="Edit" onclick="openModalEdit(${message.id})"></i> `
        actions += `<i class="fa fa-times text-danger" title="Delete" onclick="deleteMessage(${message.id})"></i> `;
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td ><b>${message.title}</b><br>${message.description}</td>
                    <td class="text-center">${activeStr(message.active)}</td>
                    ${actions}
                </tr>`;
    }

    function activeStr(active) {
        if (active == 1) {
            return 'Active';
        } else {
            return 'Inactive';
        }
    }

    function deleteMessage(id) {
        $('#loader').show();
        fetch(`<?= BASEURL ?>messages/delete/api/${id}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        });
        location.reload();
    }

    function generateTable() {
        if (total > partial) {
            $('#loader').show();
            fetch(`<?= BASEURL ?>messages/api/?index=${index}&title=${title}&active=${active}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#loader').hide();
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    let options = json.message.map(generateMessagesTable);
                    $("#messagesTable tbody").append(options);

                });
            });
        }
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });

    $(document).ready(function () {
        $('input:file').change(function (e) {
            let input = e.target;

            if (input.files.length > 0) {
                input.parentElement.classList.remove('btn-primary');
                input.parentElement.classList.remove('btn-danger');
                input.parentElement.classList.add('btn-success');
                input.text = input.value;
                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = input.value;
            } else {
                input.parentElement.classList.remove('btn-success');
                input.parentElement.classList.add('btn-danger');
                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = document.getElementById(labelId).getAttribute('default');
            }
        });
    });

    function openModalEdit(id) {

        document.getElementById('addMessage').reset();
        document.getElementById('messageId').value = id;
        $('#modal').modal('show');
        $('#message').hide();
        if (id > 0) {
            showLoading();
            fetch(`<?= BASEURL ?>messages/api/${id}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    json = json.message[0];
                    closeLoading();
                    document.getElementById('title').value = json.title;
                    document.getElementById('active').value = json.active;
                    document.getElementById('description').value = json.description;
                });
            });
        }
    }
</script>
