<div class="row">
    <div class="col">
        <div class="card p-3">
            <div class="row">
                <div class="col">
                    <div class="row">
                        <div class="col">
                            <h4 class="title"><?= $message->getTitle() ?></h4>
                        </div>
                    </div>
                    <div class="row" style="font-size: 12px">
                        <div class="col-md-4 my-auto">
                            <i class="fa fa-calendar mr-2"> </i><?= $message->getDate()->format('d/m/Y') ?>
                            <i class="fa fa-clock mr-2 ml-2"> </i><?= $message->getDate()->format('H:i') ?>
                            <i class="fa fa-user mr-2 ml-2"> </i><?= $message->getUser()->getName() ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col text-justify mt-4">
                            <?= $message->getDescription() ?>
                        </div>
                    </div>
                    <?php if ($message->getDocumentFile() != ''): ?>
                    <div class="row">
                        <div class="col">
                            <a href="<?= BASEURL ?>/uploads/<?= $message->getDocumentFile() ?>" target="_blank">
                                <i class="fa fa-3x fa-file-pdf-o"></i>
                            </a>
                        </div>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>