<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>Excent - Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale = 1, shrink-to-fit=no">
    <link rel="icon" href="<?= BASEURL ?>assets/img/sisgg.png">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/libs/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/css/login.css">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/css/style.css">
    <script src="<?= BASEURL ?>assets/js/core/jquery.min.js"></script>
    <link rel="icon" href="<?= BASEURL ?>assets/img/icon.png">
</head>

<body>

<div class="row" style="height: 100%">
    <div class="col-md-6 bg-dark">
        <div class="row mx-auto my-auto" style="height: 100%; width: 100%">
            <img src="<?= BASEURL ?>assets/img/logobranco.png" class="my-auto mx-auto" style="height: 100px"
                 alt="logo Excent">
        </div>
    </div>
    <div class="col-md-6">
        <div class="row mx-auto my-auto" style="height: 100%; width: 100%">
            <div class="col-md-2"></div>
            <div class="col-md-8 my-auto mx-auto">
                <?php if ($valid): ?>
                <form id="recover">
                    <input type="hidden" name="id" value="<?= $id ?>">
                    <div class="form-group">
                        <label for="password">Senha</label>
                        <input name="password" required id="password" class="form-control" placeholder="Senha"
                               type="password">
                    </div>
                    <div class="form-group">
                        <label for="password2">Confirme a senha</label>
                        <input name="password2" required id="password2" class="form-control"
                               placeholder="Confirme a senha" type="password">
                    </div>
                    <button class="btn btn-primary btn-block" id="recoverButton">Change Password</button>
                    <div class="text-center">
                        <a href="<?= BASEURL ?>login" class="d-block small">Sign In</a>
                    </div>
                    <div class="row">
                        <div id="message" class="alert" style="display: none"></div>
                    </div>
                </form>
                <div id="loader" class="loader"></div>
            </div>
        </div>
    </div>

</body>


<script>
    const form = document.getElementById('recover');
    const message = document.getElementById('message');

    form.addEventListener('submit', e => {
        e.preventDefault();
        $('#recoverButton').addClass('disabled');
        $('#loader').show();
        let url = "<?= BASEURL ?>recuperar/";
        let formData = formDataToJson('recover');
        fetch(url, {
            method: 'PUT',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            $('#loader').hide();
            $('#recoverButton').removeClass('disabled');
            response.json().then(json => {
                message.textContent = json.message;
                message.style.display = 'block';
                if (response.status === 201) {
                    message.classList.add("alert-success");
                    message.classList.remove("alert-danger");
                    form.reset();
                    window.location.href = '<?= BASEURL ?>login';
                } else {
                    message.classList.add("alert-danger");
                    message.classList.remove("alert-success");
                }
            });
        });
    });
</script>

<?php else: ?>

    <div class="container">
        <div class="card card-login mx-auto mt-5">
            <div class="card-header text-center">
                <img src="<?= BASEURL ?>assets/img/sisgg.png" style="height: 100px">
            </div>
            <div class="card-body">
                <div id="message" class="alert alert-danger">O Link é inválido</div>
            </div>
        </div>
    </div>

<?php endif; ?>

</body>
</html>