<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>Excent - Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale = 1, shrink-to-fit=no">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/libs/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/css/login.css">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/css/style.css">
    <script src="<?= BASEURL ?>assets/js/core/jquery.min.js"></script>
    <link rel="icon" href="<?= BASEURL ?>assets/img/icon.png">
</head>

<body>

<div class="row" style="height: 100%">
    <div class="col-md-6 bg-dark">
<!--        <div>-->
<!--            <video autoplay src="--><?//= BASEURL ?><!--assets/video/login.mp4" type="video/mp4" class="bg_video"></video>-->
<!--        </div>-->
        <div class="row mx-auto my-auto" style="height: 100%; width: 100%">
            <img src="<?= BASEURL ?>assets/img/logobranco.png" class="my-auto mx-auto" style="height: 100px"
                 alt="logo Excent">
        </div>
    </div>
    <div class="col-md-6">
        <div class="row mx-auto my-auto" style="height: 100%; width: 100%">
            <div class="col-md-2"></div>
            <div class="col-md-8 my-auto mx-auto">
                <div class="row">
                    <div class="col">
                        <h3 class="title text-center">Welcome!</h3>
                        <form method="post">
                            <div class="form-group mt-5">
                                <input id="email" name="email" type="email" class="form-control" required placeholder="Email">
                            </div>
                            <div class="form-group mt-4">
                                <input id="password" name="password" type="password" class="form-control"
                                placeholder="Password" required>
                            </div>
                            <button class="btn btn-primary btn-block mt-3">Sign In</button>
                            <div class="text-center mt-4">
                                <a href="<?= BASEURL ?>recuperar/" class="d-block small">Forgot your Password?</a>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <?php if (\App\Helpers\Session::get('errorMsg')): ?>
                            <div class="alert alert-danger text-center"><?= \App\Helpers\Session::get('errorMsg') ?></div>
                            <?php \App\Helpers\Session::forgot('errorMsg'); ?>
                        <?php endif; ?>
                        <div id="loader" class="loader"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-2">

            </div>
        </div>
    </div>
</div>


</body>