<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>Excent - Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale = 1, shrink-to-fit=no">
    <link rel="icon" href="<?= BASEURL ?>assets/img/sisgg.png">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/libs/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/css/login.css">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/css/style.css">
    <script src="<?= BASEURL ?>assets/js/core/jquery.min.js"></script>
    <link rel="icon" href="<?= BASEURL ?>assets/img/icon.png">
</head>

<body>

<div class="row" style="height: 100%">
    <div class="col-md-6 bg-dark">
        <div class="row mx-auto my-auto" style="height: 100%; width: 100%">
            <img src="<?= BASEURL ?>assets/img/logobranco.png" class="my-auto mx-auto" style="height: 100px"
                 alt="logo Excent">
        </div>
    </div>
    <div class="col-md-6">
        <div class="row mx-auto my-auto" style="height: 100%; width: 100%">
            <div class="col-md-2"></div>
            <div class="col-md-8 my-auto mx-auto">
                <form id="recover">
                    <div id="message" class="alert" style="display: none"></div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input name="email" type="email" required id="email" class="form-control" placeholder="Email">
                    </div>
                    <button class="btn btn-primary btn-block" id="recoverButton">Recuperar</button>
                    <div class="text-center">
                        <a href="<?= BASEURL?>login" class="d-block small">Login</a>
                    </div>
                </form>
                <div id="loader" class="loader"></div>
            </div>
            <div class="col-md-2">

            </div>
        </div>
    </div>
</div>

</body>

<script>
    const form = document.getElementById('recover');
    const message = document.getElementById('message');

    form.addEventListener('submit', e => {
        $('#recoverButton').addClass('disabled');
        $('#loader').show();
        e.preventDefault();
        let formData = formDataToJson('recover');
        fetch('<?= BASEURL ?>recuperar/', {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            $('#loader').hide();
            $('#recoverButton').removeClass('disabled');
            response.json().then(json => {
                message.textContent = json.message;
                message.style.display = 'block';
                if (response.status === 201) {
                    message.classList.add("alert-success");
                    message.classList.remove("alert-danger");
                    formAdd.reset();
                } else {
                    message.classList.add("alert-danger");
                    message.classList.remove("alert-success");
                }
            });
        });
    });
</script>

</body>
</html>