<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>Excent - Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale = 1, shrink-to-fit=no">
    <link rel="icon" href="<?= BASEURL ?>assets/img/sisgg.png">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/libs/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/css/login.css">
    <link rel="stylesheet" href="<?= BASEURL ?>assets/css/style.css">
    <script src="<?= BASEURL ?>assets/js/core/jquery.min.js"></script>
    <script src="<?= BASEURL ?>assets/js/functions.js"></script>
    <link rel="icon" href="<?= BASEURL ?>assets/img/icon.png">
</head>

<body>

<div class="row" style="height: 100%">
    <div class="banner">
        <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
            <source src="<?= BASEURL ?>assets/img/video/login.mp4" type="video/mp4">
        </video>
    </div>
    <div class="col">
        <div class="row mx-auto my-auto" style="height: 100%; width: 100%; position: relative; z-index: 2;">
            <div class="col-md-4"></div>
            <div class="col-md-4 my-auto mx-auto">
                <div class="row">
                    <div class="col text-center">
                        <img src="<?= BASEURL ?>assets/img/logobranco.png" alt="logo Excent">
                        <form id="recoverPassword">
                            <div id="message" class="alert" style="display: none"></div>
                            <div class="form-group mt-4">
                                <input name="email" type="email" required id="email" class="form-control" placeholder="Email">
                            </div>
                            <button class="btn btn-primary btn-block" id="recoverButton">Recover</button>
                            <div class="text-center mt-2">
                                <a href="<?= BASEURL?>login" class="d-block small">Sign In</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-4">

            </div>
        </div>
    </div>
</div>

</body>

<script>
    const form = document.getElementById('recoverPassword');
    const message = document.getElementById('message');

    form.addEventListener('submit', e => {
        $('#recoverButton').addClass('disabled');
        $('#loader').show();
        e.preventDefault();
        let formData = formDataToJson('recoverPassword');
        fetch('<?= BASEURL ?>recuperar/', {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            $('#loader').hide();
            $('#recoverButton').removeClass('disabled');
            response.json().then(json => {
                message.textContent = json.message;
                message.style.display = 'block';
                if (response.status === 201) {
                    message.classList.add("alert-success");
                    message.classList.remove("alert-danger");
                    formAdd.reset();
                } else {
                    message.classList.add("alert-danger");
                    message.classList.remove("alert-success");
                }
            });
        });
    });
</script>

</body>
</html>