<div class="row">
    <div class="col">
        <div class="card p-3">
            <div class="row">
                <div class="col-md-4">
                    <div class="row">
                        <a class="btn btn-primary text-white" href="#" onclick="openModalClass()"><i
                                    class="fa fa-plus"></i> Category</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col">
        <div class="card p-3">
            <div class="row">
                <div class="col">
                    <p id="text">Showing <span id="partial"></span> of <span id="total"></span></p>
                    <table class="table table-bordered table-striped" id="caegoriesTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th class="text-center">Category</th>
                            <th class="text-center">Status</th>
                            <th class="text-center">Actions</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<!--------------------Modal Cadastro Categoria---------------------------------->
<div class="modal fade" id="modalClass" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Category Document Registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addDocumentClass" method="post">
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label for="nameCategory">Name Category</label>
                            <input id="nameCategory" name="nameCategory" class="form-control" type="text"
                                   placeholder="Name Category">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="active">Status</label>
                            <select id="active" name="active" class="form-control">
                                <option value="1">Active</option>
                                <option value="0">Inactive</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save Category</button>
                    </div>
                </div>
                <div style="display: none" id="messageCategory" class="alert alert-danger" role="alert"></div>
            </form>
        </div>
    </div>
</div>


<script>

    var index = 0;
    var partial = 0;
    var total = 1;

    function openModalClass() {
        $('#modalClass').modal('show');
        $('#message').hide();
        document.getElementById('addDocumentClass').reset();
    }

    const divMessageCategory = document.getElementById('messageCategory');
    const formAddCategory = document.getElementById('addDocumentClass');

    formAddCategory.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let method = 'POST';
        let formData = formDataToJson('addDocument');
        fetch("<?= BASEURL ?>documents/register/category", {
            method: method,
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
            },
            body: new FormData(formAddCategory)
        }).then(response => {
            closeLoading();
            divMessageCategory.classList.add("alert-danger");
            divMessageCategory.classList.remove("alert-success");
            $('#save').removeClass('disabled');
            response.json().then(json => {
                divMessageCategory.textContent = json.message;
                divMessageCategory.style.display = 'block';
                if (response.status === 201) {
                    divMessageCategory.classList.add("alert-success");
                    divMessageCategory.classList.remove("alert-danger");
                    formAddCategory.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    function generateCategoriesTable(category) {
        let actions = '';
        actions += `<i class="fa fa-times text-danger ml-2" title="Delete" onclick="deleteCategory(${category.id})"></i> `;
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td class="text-center">${category.nameCategory}</td>
                    <td class="text-center">${activeStr(category.active)}</td>
                    ${actions}
                </tr>`;
    }

    function deleteCategory(id) {
        $('#loader').show();
        fetch(`<?= BASEURL ?>api/documents/category/delete/${id}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        });
        location.reload();
    }

    function activeStr(active) {
        if (active == 1) {
            return 'Active';
        } else {
            return 'Inactive';
        }
    }


    function generateTable() {
        if (total > partial) {
            $('#loader').show();
            fetch(`<?= BASEURL ?>api/documents/category/?index=${index}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#loader').hide();
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    let options = json.message.map(generateCategoriesTable);
                    $("#caegoriesTable tbody").append(options);

                });
            });
        }
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });


</script>