<div class="row">
    <div class="col">
        <div class="card p-3">
            <div class="row">
                <div class="col-md-6">
                    <h5 class="title my-auto">Company Files</h5>
                </div>
                <div class="col-md-6 text-right my-auto">
                    <a class="btn btn-primary text-white ml-2" href="#" onclick="openModalFolder()"><i
                                class="fa fa-plus"></i> Folder</a>
                </div>
            </div>
            <div class="row mt-4">
                <?php foreach ($folders as $folder): ?>
                    <div class="col-md-6 ">
                        <div class="col test p-3 d-flex justify-content-between"
                             onmouseover="mostraLixeira('<?= $folder->getFolder() ?>')"
                             onmouseout="escondeLixeira('<?= $folder->getFolder() ?>')">
                            <a href="<?= BASEURL ?>documents/company-files/<?= $folder->getId() ?>/?dir=<?= $folder->getFolder() ?>/"
                               style="text-decoration: none; color: black">
                                <img src="<?= BASEURL ?>assets/img/pasta16.png" alt="folder">
                                <?= $folder->getName() ?>
                                <span class="text-muted" style="font-size: 10px">
                                    <?= date('d/m/Y H:i:s', filectime($folder->getFolder())) ?>
                                </span>
                                <a>
                                    <i class="fa fa-trash-o" style="color: white" id="<?= $folder->getFolder() ?>"
                                       onclick="deleteFolder('<?= $folder->getId() ?>','<?= $folder->getFolder() ?>')"></i>

                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="row mt-3">
                <div class="col">
                    <div style="display: none" id="messageFolderDelete" class="alert alert-danger" role="alert"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<!------------------------- Modal Cadastro Folder-------------------------------------->
<div class="modal fade" id="modalFolder" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Folder Registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addFolder" method="post">
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label for="nameFolder">Name</label>
                            <input id="nameFolder" name="nameFolder" class="form-control" type="text"
                                   placeholder="Name">
                            <input id="destinyFolder" name="destiny" class="form-control" type="hidden"
                                   value="<?= $baseDir ?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save Folder</button>
                    </div>
                </div>
                <div style="display: none" id="messageFolder" class="alert alert-danger" role="alert"></div>
            </form>
        </div>
    </div>
</div>
<script>

    function openModalFolder() {
        $('#modalFolder').modal('show');
        $('#message').hide();
        document.getElementById('addDocument').reset();
    }

    const formAddFolder = document.getElementById('addFolder');
    const divMessageFolder = document.getElementById('messageFolder');
    const divMessageFolderDelete = document.getElementById('messageFolderDelete');

    formAddFolder.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let method = 'POST';
        let formData = formDataToJson('addFolder');
        fetch("<?= BASEURL ?>documents/company-files/register-folder", {
            method: method,
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
            },
            body: new FormData(formAddFolder)
        }).then(response => {
            closeLoading();
            divMessageFolder.classList.add("alert-danger");
            divMessageFolder.classList.remove("alert-success");
            $('#save').removeClass('disabled');
            response.json().then(json => {
                divMessageFolder.textContent = json.message;
                divMessageFolder.style.display = 'block';
                if (response.status === 201) {
                    divMessageFolder.classList.add("alert-success");
                    divMessageFolder.classList.remove("alert-danger");
                    formAddFolder.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    function mostraLixeira(id) {
        document.getElementById(id).style.color = 'black';
    }

    function escondeLixeira(id) {
        document.getElementById(id).style.color = 'white';
    }

    function deleteFolder(id, dir) {

        var result = confirm('Are you sure about that?\nYour action will be permanent and you will not be able to recover the deleted data!');
        if (result == true) {
            showLoading();
            fetch(`<?= BASEURL ?>documents/delete/?id=${id}&dir=${dir}`, {
                method: 'get',
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                },
            }).then(response => {
                closeLoading();
                divMessageFolderDelete.classList.add("alert-danger");
                divMessageFolderDelete.classList.remove("alert-success");
                response.json().then(json => {
                    divMessageFolderDelete.textContent = json.message;
                    divMessageFolderDelete.style.display = 'block';
                    if (response.status === 201) {
                        divMessageFolderDelete.classList.add("alert-success");
                        divMessageFolderDelete.classList.remove("alert-danger");
                    }
                });
                setTimeout(function () {
                    location.reload();
                }, 1500);
            });
        } else {
            return false;
        }

    }

</script>
