<div class="row">
    <div class="col">
        <div class="card p-3">
            <form id="filter">
                <div class="row">
                    <div class="col-md-2">
                        <div class="row">
                            <a class="btn btn-primary text-white ml-2" href="#" onclick="openModalFolder()"><i
                                        class="fa fa-plus"></i> Folder</a>
                        </div>
                    </div>
                    <div class="col-md-7 my-auto">
                        <div class="form-group mt-2">
                            <input class="form-control" id="titleFilter" name="title" type="text" placeholder="Name">
                        </div>
                    </div>
                    <div class="col-md-3 text-right">
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Cancel</button>
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card p-3">
            <p id="text">Showing <span id="partial"></span> of <span id="total"></span></p>
            <table class="table table-sm table-hover" id="documentsTable" width="100%" cellspacing="0">
                <thead class="thead-light">
                <tr>
                    <th class="text-center">#</th>
                    <th class="text-center">Date</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Manage</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

<!------------------------- Modal Cadastro Folder-------------------------------------->
<div class="modal fade" id="modalFolder" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Folder Registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addFolder" method="post">
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label for="nameFolder">Name</label>
                            <input id="nameFolder" name="nameFolder" class="form-control" type="text" placeholder="Name">
                            <input id="destinyFolder" name="destiny" class="form-control" type="hidden"
                            value="<?= $baseDir ?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save Folder</button>
                    </div>
                </div>
                <div style="display: none" id="messageFolder" class="alert alert-danger" role="alert"></div>
            </form>
        </div>
    </div>
</div>
<script>

    var index = 0;
    var partial = 0;
    var total = 1;
    var title = 0;

    function openModalFolder() {
        $('#modalFolder').modal('show');
        $('#message').hide();
        document.getElementById('addDocument').reset();
    }

    const formAddFolder = document.getElementById('addFolder');
    const divMessageFolder = document.getElementById('messageFolder');

    formAddFolder.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let method = 'POST';
        let formData = formDataToJson('addFolder');
        fetch("<?= BASEURL ?>documents/company-files/register-folder", {
            method: method,
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
            },
            body: new FormData(formAddFolder)
        }).then(response => {
            closeLoading();
            divMessageFolder.classList.add("alert-danger");
            divMessageFolder.classList.remove("alert-success");
            $('#save').removeClass('disabled');
            response.json().then(json => {
                divMessageFolder.textContent = json.message;
                divMessageFolder.style.display = 'block';
                if (response.status === 201) {
                    divMessageFolder.classList.add("alert-success");
                    divMessageFolder.classList.remove("alert-danger");
                    formAddDocument.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        title = formData.title;
        $("#documentsTable tbody").empty();
        generateTable();
    });

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        title = 0;
        $("#documentsTable tbody").empty();
        generateTable();
    }


    function generateDocumentsTable(folder) {
        let actions = '';
        actions += `<i class="fa fa-times text-danger" title="Delete" onclick="openModalEdit(${folder.id})"></i> `
        actions = `<td class="text-center">${actions} </td>`;
        let view = `${folder.id}/?dir=${folder.folder}`;
        return `<tr>
                    <td class="text-center"><i class="fa fa-folder"></i></td>
                    <td class="text-center">${folder.date}</td>
                    <td class="text-center"><a href="${folderView(view)}">${folder.name}<a></td>
                    <td class="text-center"><button class="btn btn-primary btn-sm">Users</button></td>
                    ${actions}
                </tr>`;
    }

    function folderView(id) {
        return `<?= BASEURL ?>documents/company-files/${id}`;
    }

    function generateTable() {

        $('#loader').show();
        fetch(`<?= BASEURL ?>api/documents/company-files/?index=${index}&title=${title}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                $('#loader').hide();
                $('#total').text(json.total);
                $('#partial').text(json.partial);
                total = json.total;
                partial = json.partial;
                let options = json.message.map(generateDocumentsTable);
                $("#documentsTable tbody").append(options);

            });
        });
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });
</script>
