<div class="row">
    <div class="col">
        <div class="card p-3">
            <form id="filter">
                <div class="row">
                    <div class="col-md-3">
                        <div class="row">
                            <a class="btn btn-primary text-white" href="#" onclick="openModal()"><i
                                        class="fa fa-plus"></i> Document</a>
                        </div>
                    </div>
                    <div class="col-md-6 my-auto">
                        <div class="form-group mt-2">
                            <input class="form-control" id="titleFilter" name="title" type="text" placeholder="Title">
                        </div>
                    </div>
                    <div class="col-md-3 text-right">
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Cancel</button>
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card p-3">
            <div class="row">
                <div class="col">
                    <ul class="nav nav-tabs nav-justified">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#all" onclick="selectCategory(0)">All</a>
                        </li>
                        <?php foreach ($categories as $category): ?>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#all"
                                   onclick="selectCategory(<?= $category->getId() ?>)"><?= $category->getNameCategory() ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col">
                    <p id="text">Showing <span id="partial"></span> of <span id="total"></span></p>
                    <table class="table table-bordered table-striped" id="documentsTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th class="text-center"></th>
                            <th class="text-center">Description</th>
                            <th class="text-center">Actions</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!------------------------- Modal Cadastro-------------------------------------->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Document Registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addDocument" method="post">
                <div class="form-group">
                    <input type="hidden" name="documentId" id="documentId">
                    <div class="row">
                        <div class="col">
                            <label for="title">Title</label>
                            <input id="title" name="title" class="form-control" type="text" placeholder="Title">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="descriptionDocument">Description</label>
                            <textarea id="descriptionDocument" name="description" class="form-control" type="text"
                                      placeholder="Description"></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 mt-1">
                            <label for="type">Category</label>
                            <select id="type" name="type" class="form-control">
                                <option value="0">Select Category</option>
                                <?php foreach ($categories as $category): ?>
                                    <option value="<?= $category->getId() ?>"><?= $category->getNameCategory() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <?php if ($user->getType() == 1 || $user->getTtpe() == 2): ?>
                        <div class="col-md-4 mt-1">
                            <label for="destiny">Destiny</label>
                            <select id="destiny" name="destiny" class="form-control">
                                <option value="0">Select Destiny</option>
                                <?php if ($user->getType() == 1): ?>
                                <option value="2">Admin</option>
                                <?php endif; ?>
                                <option value="3">Manager</option>
                                <option value="4">Advisor</option>
                                <option value="5">Human Resources</option>
                            </select>
                        </div>
                        <?php endif; ?>
                        <div class="col-md-4 mt-4">
                            <div class="form-group mt-3">
                                <span class="fileselector">
                                    <label class="btn btn-block btn-danger text-white" style="margin-top: 5px"
                                           for="projectFile">
                                        <input class="upload-file-selector" id="projectFile" type="file"
                                               name="projectFile">
                                        <i class="fa fa-paperclip margin-correction"></i>
                                            <span id="projectFileLabel" default="Attach File">Attach File</span>
                                    </label>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save Document</button>
                    </div>
                </div>
                <div style="display: none" id="messageDocument" class="alert alert-danger" role="alert"></div>
            </form>
        </div>
    </div>
</div>


<script src="<?= BASEURL ?>assets/js/plugins/tinymce/jquery.tinymce.min.js"></script>
<script src="<?= BASEURL ?>assets/js/plugins/tinymce/tinymce.min.js"></script>
<script>tinymce.init({
        selector: "textarea",
        menubar: false,
        statusbar: false,
        toolbar: 'styleselect | bold italic | fontsizeselect | alignleft aligncenter alignright alignjustify | bullist numlist | link image media | forecolor backcolor table',
        plugins: ["lists link image media textcolor table"],
        browser_spellcheck: true,
        imagetools_cors_hosts: ['www.tinymce.com', 'codepen.io'],
        setup: function (editor) {
            editor.on('change', function () {
                editor.save();
            });
        }
    });
</script>

<script>

    var index = 0;
    var partial = 0;
    var total = 1;
    var title = 0;
    var type = 0;

    function openModal() {
        $('#modal').modal('show');
        $('#message').hide();
        document.getElementById('addDocument').reset();
    }

    const formAddDocument = document.getElementById('addDocument');
    const divMessageDocument = document.getElementById('messageDocument');

    formAddDocument.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let method = 'POST';
        let formData = formDataToJson('addDocument');
        fetch("<?= BASEURL ?>documents/register", {
            method: method,
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
            },
            body: new FormData(formAddDocument)
        }).then(response => {
            closeLoading();
            divMessageDocument.classList.add("alert-danger");
            divMessageDocument.classList.remove("alert-success");
            $('#save').removeClass('disabled');
            response.json().then(json => {
                divMessageDocument.textContent = json.message;
                divMessageDocument.style.display = 'block';
                if (response.status === 201) {
                    divMessageDocument.classList.add("alert-success");
                    divMessageDocument.classList.remove("alert-danger");
                    formAddDocument.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    function openModalEdit(id) {

        $('#modal').modal('show');
        $('#message').hide();
        if (id > 0) {
            showLoading();
            fetch(`<?= BASEURL ?>documents/api/${id}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    json = json.message[0];
                    closeLoading();
                    document.getElementById('title').value = json.title;
                    document.getElementById('descriptionDocument').value = json.description;
                    document.getElementById('type').value = json.type;
                });
            });
        }
    }

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        title = formData.title;
        $("#documentsTable tbody").empty();
        generateTable();
    });

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        title = 0;
        $("#documentsTable tbody").empty();
        generateTable();
    }


    function generateDocumentsTable(document) {
        let actions = '';
        actions += `<i class="fa fa-pencil text-info" title="Edit" onclick="openModalEdit(${document.id})"></i> `
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td class="text-center px-4"><a href="${documentView(document.documentFile)}" target="_blank"><i class="fa fa-3x fa-file-pdf-o"></i><a></td>
                    <td ><b>${document.title}</b><br>${document.description}
                    <div class="float-right" style="font-size: 12px"><i class="fa fa-calendar py-2"></i> ${document.date}
                            <i class="fa fa-clock ml-2 py-2"> </i> ${document.time}</div></td>
                    ${actions}
                </tr>`;
    }

    function documentView(id) {
        return `<?= BASEURL ?>uploads/${id}`;
    }

    function selectCategory(id) {
        index = 0;
        type = id;
        $("#documentsTable tbody").empty();
        generateTable();
    }

    function generateTable() {

        $('#loader').show();
        fetch(`<?= BASEURL ?>documents/sent/api/?index=${index}&title=${title}&type=${type}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                $('#loader').hide();
                $('#total').text(json.total);
                $('#partial').text(json.partial);
                total = json.total;
                partial = json.partial;
                let options = json.message.map(generateDocumentsTable);
                $("#documentsTable tbody").append(options);

            });
        });
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });

    $(document).ready(function () {
        $('input:file').change(function (e) {
            let input = e.target;

            if (input.files.length > 0) {
                input.parentElement.classList.remove('btn-primary');
                input.parentElement.classList.remove('btn-danger');
                input.parentElement.classList.add('btn-success');
                input.text = input.value;
                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = input.value;
            } else {
                input.parentElement.classList.remove('btn-success');
                input.parentElement.classList.add('btn-danger');
                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = document.getElementById(labelId).getAttribute('default');
            }
        });
    });
</script>
