<div class="row">
    <div class="col">
        <div class="card p-3">
            <div class="row">
                <div class="col">
                    <?php if ($typeAccess == 0): ?>
                    <h5 class="title my-auto">My Folder</h5>
                    <?php else: ?>
                    <h5 class="title my-auto">Folders</h5>
                    <?php endif; ?>
                </div>
                <?php if ($typeAccess == 0): ?>
                <span class="float-right">
                    <a class="btn btn-primary text-white" href="#" onclick="openModal()"><i
                                class="fa fa-plus"></i> Document</a>
                    <a class="btn btn-primary text-white ml-2" href="#" onclick="openModalFolder()"><i
                                class="fa fa-plus"></i> Folder</a>
                </span>
                <?php endif; ?>
            </div>
            <!--            <div class="row">-->
            <!--                <div class="col-md-2">-->
            <!--                    <label for="orderBy">Order By:</label>-->
            <!--                    <select id="orderBy" name="orderBy" class="form-control">-->
            <!--                        <option value="1" selected>Type</option>-->
            <!--                        <option value="2">Name</option>-->
            <!--                    </select>-->
            <!--                </div>-->
            <!--            </div>-->
            <div class="row mt-4" id="orderByType">
                <?php for ($i = 0; $i < count($types); $i++): ?>
                    <div class="col-md-2 mt-3 text-center">
                        <div class="col test" onmouseover="mostraLixeira('<?= $types[$i] ?>')"
                             onmouseout="escondeLixeira('<?= $types[$i] ?>')">
                            <?php if (is_dir($baseDir . $types[$i])): ?>
                                <a href="<?= BASEURL ?>documents/<?= $folder ?>/?dir=<?= $baseDir . $types[$i] ?>/"
                                   style="text-decoration: none; color: black">
                                    <img
                                            src="<?= BASEURL ?>assets/img/pasta.png" alt="word"
                                    ><br> <?= $types[$i] ?>
                                </a>
                                <br><i class="fa fa-trash-o p-2" style="color: white" id="<?= $types[$i] ?>"
                                       onclick="deleteFolder('<?= $baseDir . $types[$i] ?>')"></i>
                            <?php else: ?>
                                <a href="<?= BASEURL ?><?= $baseDir . $types[$i] ?>" target="_blank"
                                   style="text-decoration: none; color: black">
                                    <img
                                        <?php if (substr($types[$i], -3) == 'ocx'): ?>
                                            src="<?= BASEURL ?>assets/img/word.png" alt="word"
                                        <?php elseif (substr($types[$i], -3) == 'pdf'): ?>
                                            src="<?= BASEURL ?>assets/img/pdf.png" alt="pdf"
                                        <?php elseif (substr($types[$i], -3) == 'lsx' || substr($types[$i], -3) == 'csv'): ?>
                                            src="<?= BASEURL ?>assets/img/excel.png" alt="excel"
                                        <?php elseif (substr($types[$i], -3) == 'peg' || substr($types[$i], -3) == 'jpg' || substr($types[$i], -3) == 'png'): ?>
                                            src="<?= BASEURL ?>assets/img/imagem.png" alt="image"
                                        <?php else: ?>
                                            src="<?= BASEURL ?>assets/img/arquivo.png" alt="arquivo"
                                        <?php endif; ?>
                                    ><br> <?= $types[$i] ?>
                                </a>
                                <br><i class="fa fa-trash-o p-2" style="color: white" id="<?= $types[$i] ?>"
                                       onclick="deleteFolder('<?= $baseDir . $types[$i] ?>')"></i>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endfor; ?>
            </div>
            <div class="row mt-3">
                <div class="col">
                    <div style="display: none" id="messageFolderDelete" class="alert alert-danger" role="alert"></div>
                </div>
            </div>
            <?php if ($typeAccess == 1): ?>
                <?php if ($baseDir != 'uploads/my-folder/'): ?>
                    <div class="row">
                        <div class="col text-right">
                            <a class="btn btn-danger text-white ml-2"
                               href="<?= BASEURL ?>documents/<?= $folder ?>/?dir=<?= $backDir ?>"><i
                                        class="fa fa-chevron-circle-left"></i> Back</a>
                        </div>
                    </div>
                <?php endif; ?>
            <?php else: ?>
                <?php if ($baseDir != 'uploads/my-folder/' . $user->getFolder() . '/'): ?>
                    <div class="row">
                        <div class="col text-right">
                            <a class="btn btn-danger text-white ml-2"
                               href="<?= BASEURL ?>documents/<?= $folder ?>/?dir=<?= $backDir ?>"><i
                                        class="fa fa-chevron-circle-left"></i> Back</a>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
</div>

<!------------------------- Modal Cadastro Document-------------------------------------->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Document Registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addDocument" method="post">
                <div class="form-group">
                    <input type="hidden" name="documentId" id="documentId">
                    <div class="row">
                        <div class="col">
                            <label for="title">Title</label>
                            <input id="title" name="title" class="form-control" type="text" placeholder="Title">
                            <input id="destiny" name="destiny" class="form-control" type="hidden"
                                   value="<?= $baseDir ?>">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group mt-3">
                                <span class="fileselector">
                                    <label class="btn btn-block btn-danger text-white" style="margin-top: 5px"
                                           for="projectFile">
                                        <input class="upload-file-selector" id="projectFile" type="file"
                                               name="projectFile">
                                        <i class="fa fa-paperclip margin-correction"></i>
                                            <span id="projectFileLabel" default="Attach File">Attach File</span>
                                    </label>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save Document</button>
                    </div>
                </div>
                <div style="display: none" id="messageDocument" class="alert alert-danger" role="alert"></div>
            </form>
        </div>
    </div>
</div>

<!------------------------- Modal Cadastro Folder-------------------------------------->
<div class="modal fade" id="modalFolder" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Folder Registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addFolder" method="post">
                <div class="form-group">
                    <input type="hidden" name="FolderId" id="FolderId">
                    <div class="row">
                        <div class="col">
                            <label for="title">Title</label>
                            <input id="titleFolder" name="title" class="form-control" type="text"
                                   placeholder="Title">
                            <input id="destinyFolder" name="destiny" class="form-control" type="hidden"
                                   value="<?= $baseDir ?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save Folder</button>
                    </div>
                </div>
                <div style="display: none" id="messageFolder" class="alert alert-danger" role="alert"></div>
            </form>
        </div>
    </div>
</div>
<script>

    var index = 0;
    var partial = 0;
    var total = 1;
    var title = 0;
    const formAddDocument = document.getElementById('addDocument');
    const formAddFolder = document.getElementById('addFolder');
    const divMessageDocument = document.getElementById('messageDocument');
    const divMessageFolderDelete = document.getElementById('messageFolderDelete');
    const divMessageFolder = document.getElementById('messageFolder');


    function mostraLixeira(id) {
        document.getElementById(id).style.color = 'black';
    }

    function escondeLixeira(id) {
        document.getElementById(id).style.color = 'white';
    }

    function deleteFolder(id) {

        var result = confirm('Are you sure about that?\nYour action will be permanent and you will not be able to recover the deleted data!');
        if (result == true) {
            showLoading();
            fetch(`<?= BASEURL ?>documents/delete/?dir=${id}`, {
                method: 'get',
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                },
            }).then(response => {
                closeLoading();
                divMessageFolderDelete.classList.add("alert-danger");
                divMessageFolderDelete.classList.remove("alert-success");
                response.json().then(json => {
                    divMessageFolderDelete.textContent = json.message;
                    divMessageFolderDelete.style.display = 'block';
                    if (response.status === 201) {
                        divMessageFolderDelete.classList.add("alert-success");
                        divMessageFolderDelete.classList.remove("alert-danger");
                    }
                });
                setTimeout(function () {
                    location.reload();
                }, 1500);
            });
        } else {
            return false;
        }

    }

    function openModal() {
        $('#modal').modal('show');
        $('#message').hide();
        document.getElementById('addDocument').reset();
    }

    function openModalFolder() {
        $('#modalFolder').modal('show');
        $('#message').hide();
        document.getElementById('addDocument').reset();
    }

    formAddDocument.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let method = 'POST';
        let formData = formDataToJson('addDocument');
        fetch("<?= BASEURL ?>documents/register-document", {
            method: method,
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
            },
            body: new FormData(formAddDocument)
        }).then(response => {
            closeLoading();
            divMessageDocument.classList.add("alert-danger");
            divMessageDocument.classList.remove("alert-success");
            $('#save').removeClass('disabled');
            response.json().then(json => {
                divMessageDocument.textContent = json.message;
                divMessageDocument.style.display = 'block';
                if (response.status === 201) {
                    divMessageDocument.classList.add("alert-success");
                    divMessageDocument.classList.remove("alert-danger");
                    formAddDocument.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    formAddFolder.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let method = 'POST';
        let formData = formDataToJson('addFolder');
        fetch("<?= BASEURL ?>documents/register-folder", {
            method: method,
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
            },
            body: new FormData(formAddFolder)
        }).then(response => {
            closeLoading();
            divMessageFolder.classList.add("alert-danger");
            divMessageFolder.classList.remove("alert-success");
            $('#save').removeClass('disabled');
            response.json().then(json => {
                divMessageFolder.textContent = json.message;
                divMessageFolder.style.display = 'block';
                if (response.status === 201) {
                    divMessageFolder.classList.add("alert-success");
                    divMessageFolder.classList.remove("alert-danger");
                    formAddFolder.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    $(document).ready(function () {
        $('input:file').change(function (e) {
            let input = e.target;

            if (input.files.length > 0) {
                input.parentElement.classList.remove('btn-primary');
                input.parentElement.classList.remove('btn-danger');
                input.parentElement.classList.add('btn-success');
                input.text = input.value;
                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = input.value;
            } else {
                input.parentElement.classList.remove('btn-success');
                input.parentElement.classList.add('btn-danger');
                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = document.getElementById(labelId).getAttribute('default');
            }
        });
    });
</script>
