<div class="row">
    <div class="col">
        <div class="card p-3">
            <form id="filter">
                <div class="row">
                    <div class="col-md-3">
                        <div class="row">
                            <a class="btn btn-primary text-white" href="#" onclick="openModal()"><i
                                        class="fa fa-plus"></i> Document</a>
                        </div>
                    </div>
                    <div class="col-md-6 my-auto">
                        <div class="form-group mt-2">
                            <input class="form-control" id="titleFilter" name="title" type="text" placeholder="Title">
                        </div>
                    </div>
                    <div class="col-md-3 text-right">
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Cancel</button>
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card p-3">
            <p id="text">Showing <span id="partial"></span> of <span id="total"></span></p>
            <table class="table table-sm table-hover" id="documentsTable" width="100%" cellspacing="0">
                <thead class="thead-light">
                <tr>
                    <th class="text-center">Date</th>
                    <th class="text-center">Title</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

<!------------------------- Modal Cadastro-------------------------------------->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Document Registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addDocument" method="post">
                <div class="form-group">
                    <input type="hidden" name="documentId" id="documentId">
                    <div class="row">
                        <div class="col">
                            <label for="title">Title</label>
                            <input id="title" name="title" class="form-control" type="text" placeholder="Title">
                        </div>
                        </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group mt-3">
                                <span class="fileselector">
                                    <label class="btn btn-block btn-danger text-white" style="margin-top: 5px"
                                           for="projectFile">
                                        <input class="upload-file-selector" id="projectFile" type="file"
                                               name="projectFile">
                                        <i class="fa fa-paperclip margin-correction"></i>
                                            <span id="projectFileLabel" default="Attach File">Attach File</span>
                                    </label>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save Document</button>
                    </div>
                </div>
                <div style="display: none" id="messageDocument" class="alert alert-danger" role="alert"></div>
            </form>
        </div>
    </div>
</div>


<script src="<?= BASEURL ?>assets/js/plugins/tinymce/jquery.tinymce.min.js"></script>
<script src="<?= BASEURL ?>assets/js/plugins/tinymce/tinymce.min.js"></script>
<script>tinymce.init({
        selector: "textarea",
        menubar: false,
        statusbar: false,
        toolbar: 'styleselect | bold italic | fontsizeselect | alignleft aligncenter alignright alignjustify | bullist numlist | link image media | forecolor backcolor table',
        plugins: ["lists link image media textcolor table"],
        browser_spellcheck: true,
        imagetools_cors_hosts: ['www.tinymce.com', 'codepen.io'],
        setup: function (editor) {
            editor.on('change', function () {
                editor.save();
            });
        }
    });
</script>

<script>

    var index = 0;
    var partial = 0;
    var total = 1;
    var title = 0;

    function openModal() {
        $('#modal').modal('show');
        $('#message').hide();
        document.getElementById('addDocument').reset();
    }

    const formAddDocument = document.getElementById('addDocument');
    const divMessageDocument = document.getElementById('messageDocument');

    formAddDocument.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let method = 'POST';
        let formData = formDataToJson('addDocument');
        fetch("<?= BASEURL ?>documents/my-folder/register", {
            method: method,
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
            },
            body: new FormData(formAddDocument)
        }).then(response => {
            closeLoading();
            divMessageDocument.classList.add("alert-danger");
            divMessageDocument.classList.remove("alert-success");
            $('#save').removeClass('disabled');
            response.json().then(json => {
                divMessageDocument.textContent = json.message;
                divMessageDocument.style.display = 'block';
                if (response.status === 201) {
                    divMessageDocument.classList.add("alert-success");
                    divMessageDocument.classList.remove("alert-danger");
                    formAddDocument.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        title = formData.title;
        $("#documentsTable tbody").empty();
        generateTable();
    });

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        title = 0;
        $("#documentsTable tbody").empty();
        generateTable();
    }


    function generateDocumentsTable(document) {
        let actions = '';
        actions += `<i class="fa fa-times text-danger" title="Delete" onclick="deleteDoc(${document.id})"></i> `
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td class="text-center">${document.date}</td>
                    <td class="text-center"><a href="${documentView(document.documentFile)}" target="_blank">${document.title}<a></td>
                    ${actions}
                </tr>`;
    }

    function documentView(id) {
        return `<?= BASEURL ?>uploads/my-folder/${id}`;
    }

    function deleteDoc(id) {
        $('#loader').show();
        fetch(`<?= BASEURL ?>api/documents/my-folder/delete/${id}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        });
        location.reload();
    }

    function generateTable() {

        $('#loader').show();
        fetch(`<?= BASEURL ?>api/documents/my-folder/?index=${index}&title=${title}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                $('#loader').hide();
                $('#total').text(json.total);
                $('#partial').text(json.partial);
                total = json.total;
                partial = json.partial;
                let options = json.message.map(generateDocumentsTable);
                $("#documentsTable tbody").append(options);

            });
        });
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });

    $(document).ready(function () {
        $('input:file').change(function (e) {
            let input = e.target;

            if (input.files.length > 0) {
                input.parentElement.classList.remove('btn-primary');
                input.parentElement.classList.remove('btn-danger');
                input.parentElement.classList.add('btn-success');
                input.text = input.value;
                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = input.value;
            } else {
                input.parentElement.classList.remove('btn-success');
                input.parentElement.classList.add('btn-danger');
                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = document.getElementById(labelId).getAttribute('default');
            }
        });
    });
</script>
