<div class="row">
    <div class="col">
        <div class="card p-3">
            <form id="filter">
                <div class="row">
                    <div class="col-md-9 my-auto">
                        <div class="form-group mt-2">
                            <input class="form-control" id="titleFilter" name="title" type="text" placeholder="Title">
                        </div>
                    </div>
                    <div class="col-md-3 text-right">
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Cancel</button>
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card p-3">
            <div class="row">
                <div class="col">
                    <ul class="nav nav-tabs nav-justified">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#all" onclick="selectCategory(0)">All</a>
                        </li>
                        <?php foreach ($categories as $category): ?>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#all"
                                   onclick="selectCategory(<?= $category->getId() ?>)"><?= $category->getNameCategory() ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col">
                    <p id="text">Showing <span id="partial"></span> of <span id="total"></span></p>
                    <table class="table table-bordered table-sm" id="documentsTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th class="text-center"></th>
                            <th class="text-center">Description</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="<?= BASEURL ?>assets/js/plugins/tinymce/jquery.tinymce.min.js"></script>
<script src="<?= BASEURL ?>assets/js/plugins/tinymce/tinymce.min.js"></script>
<script>tinymce.init({
        selector: "textarea",
        menubar: false,
        statusbar: false,
        toolbar: 'styleselect | bold italic | fontsizeselect | alignleft aligncenter alignright alignjustify | bullist numlist | link image media | forecolor backcolor table',
        plugins: ["lists link image media textcolor table"],
        browser_spellcheck: true,
        imagetools_cors_hosts: ['www.tinymce.com', 'codepen.io'],
        setup: function (editor) {
            editor.on('change', function () {
                editor.save();
            });
        }
    });
</script>

<script>

    var index = 0;
    var partial = 0;
    var total = 1;
    var title = 0;
    var type = 0;
    var received = <?= $user->getId() ?>;


    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        title = formData.title;
        $("#documentsTable tbody").empty();
        generateTable();
    });

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        title = 0;
        $("#documentsTable tbody").empty();
        generateTable();
    }


    function generateDocumentsTable(document) {
        let status = '';
        if (document.status == 0) status = `<div class="text-success ml-3"><i class="fa fa-check"></i></div>`;
        return `<tr>
                    <td class="text-center px-4"><a href="${documentView(document.documentFile)}" target="_blank" onclick="updateStatus(${document.id})"><i class="fa fa-3x fa-file-pdf-o"></i><a></td>
                    <td class="text-justify"><div class="row"> <b>${document.title} </b> ${status}</div><br>${document.description}
                    <div class="float-right" style="font-size: 12px"><i class="fa fa-calendar py-2"></i> ${document.date}
                            <i class="fa fa-clock ml-2 py-2"> </i> ${document.time}</div></td>
                </tr>`;
    }

    function documentView(id) {
        return `<?= BASEURL ?>uploads/${id}`;
    }

    function selectCategory(id) {
        index = 0;
        type = id;
        $("#documentsTable tbody").empty();
        generateTable();
    }
    
    function updateStatus(id) {
        fetch(`<?= BASEURL ?>documents/update/api/${id}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        })
    }

    function generateTable() {

        $('#loader').show();
        fetch(`<?= BASEURL ?>documents/received/api/?index=${index}&title=${title}&type=${type}&received=${received}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                $('#loader').hide();
                $('#total').text(json.total);
                $('#partial').text(json.partial);
                total = json.total;
                partial = json.partial;
                let options = json.message.map(generateDocumentsTable);
                $("#documentsTable tbody").append(options);

            });
        });
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });

    $(document).ready(function () {
        $('input:file').change(function (e) {
            let input = e.target;

            if (input.files.length > 0) {
                input.parentElement.classList.remove('btn-primary');
                input.parentElement.classList.remove('btn-danger');
                input.parentElement.classList.add('btn-success');
                input.text = input.value;
                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = input.value;
            } else {
                input.parentElement.classList.remove('btn-success');
                input.parentElement.classList.add('btn-danger');
                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = document.getElementById(labelId).getAttribute('default');
            }
        });
    });
</script>
