<div class="row">
    <div class="col">
        <div class="card p-3">
            <div class="row">
                <div class="col">
                    <div class="row">
                        <div class="col">
                            <a href="<?= BASEURL ?>/uploads/<?= $doc->getDocumentFile() ?>" target="_blank">
                                <h4 class="title"><?= $doc->getTitle() ?></h4>
                            </a>
                        </div>
                    </div>
                    <div class="row" style="font-size: 12px">
                        <div class="col">
                            <i class="fa fa-calendar mr-2"> </i><?= $doc->getCreated()->format('d/m/Y') ?>
                            <i class="fa fa-clock mr-2 ml-2"> </i><?= $doc->getCreated()->format('H:i') ?>
                            <i class="fa fa-user mr-2 ml-2"> </i><?= $doc->getResponsible()->getName() ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col text-justify mt-4">
                            <?= $doc->getDescription() ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>