<div class="row">
    <div class="col">
        <div class="card p-3">
            <form id="filter">
                <div class="row">
                    <div class="col-md-2">
                        <a class="btn btn-primary text-white" href="#" onclick="openModal()"><i
                                    class="fa fa-plus"></i> User</a>
                    </div>
                    <div class="col-md-4 my-auto">
                        <div class="form-group mt-2">
                            <input class="form-control" id="nameFilter" name="name" type="text" placeholder="Name">
                        </div>
                    </div>
                    <?php if ($user->getType() < 3): ?>
                        <div class="col-md-3 my-auto">
                            <div class="form-group mt-2">
                                <select name="type" id="typeFilter" class="form-control">
                                    <option value="0">Select Type</option>
                                    <?php if ($user->getType() == 1): ?>
                                        <option value="1">Master</option>
                                        <option value="2">Admin</option>
                                    <?php endif; ?>
                                    <option value="3">Manager</option>
                                    <option value="4">Advisor</option>
                                    <option value="5">Human Resources</option>
                                </select>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="col text-right">
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Cancel</button>
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="row">
    <div class="col">
        <div class="card p-3">
            <div class="row table-responsive-lg">
                <div class="col">
                    <p>Showing <span id="partial"></span> of <span id="total"></span></p>

                        <table class="table table-sm table-hover table-bordered" id="usersTable">
                            <thead>
                            <tr>
                                <th class="text-center">Name</th>
                                <th class="text-center">Type</th>
                                <th class="text-center">Email</th>
                                <th class="text-center">Status</th>
                                <th class="text-center">Actions</th>
                            </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal Cadastro-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">User Registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addUser" method="post">
                <div class="form-group">
                    <input type="hidden" name="userId" id="userIdEdit">
                    <div class="row">
                        <div class="col">
                            <label for="nameEdit">Name</label>
                            <input id="nameEdit" name="name" class="form-control" type="text" placeholder="Name">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="emailEdit">Email</label>
                            <input id="emailEdit" name="email" class="form-control" type="email" placeholder="Email">
                        </div>
                    </div>
                    <?php if ($user->getType() < 3): ?>
                        <div class="row">
                            <div class="col-md-6">
                                <label for="typeEdit">Type</label>
                                <select id="typeEdit" name="type" class="form-control" onchange="selectManager()">
                                    <option value="0">Select Type</option>
                                    <?php if ($user->getType() == 1): ?>
                                        <option value="1">Master</option>
                                        <option value="2">Admin</option>
                                    <?php endif; ?>
                                    <option value="3">Manager</option>
                                    <option value="4">Advisor</option>
                                    <option value="5">Human Resources</option>
                                </select>
                            </div>
                            <div class="col-md-6" id="userManager" style="display: none">
                                <label for="managerEdit">Manager</label>
                                <select id="managerEdit" name="manager" class="form-control">
                                    <option value="0">Select Manager</option>
                                    <?php foreach ($users as $us): ?>
                                        <option value="<?= $us->getId() ?>"><?= $us->getName() ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if ($user->getType() == 3): ?>
                        <input type="hidden" name="manager" value="<?= $user->getId() ?>">
                        <input type="hidden" name="type" value="4">
                    <?php endif; ?>
                    <div class="row">
                        <div class="col">
                            <label for="countryEdit">Country</label>
                            <select id="countryEdit" name="country" class="form-control">
                                <option value="0">Select Country</option>
                                <?php foreach ($countries as $country): ?>
                                    <option value="<?= $country->getId() ?>"><?= $country->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <label for="passwordEdit">Password</label>
                            <input id="passwordEdit" name="password" class="form-control" type="text"
                                   placeholder="Password">
                            <span style="font-size: 8px; color: grey; margin-left: 5px">Minimum 8 characters</span>
                        </div>
                        <div class="col-md-4">
                            <label for="activeEdit">Status</label>
                            <select id="activeEdit" name="active" class="form-control">
                                <option value="1">Active</option>
                                <option value="0">Inactive</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save User</button>
                    </div>
                </div>
                <div style="display: none" id="message" class="alert alert-danger" role="alert"></div>
            </form>
        </div>
    </div>
</div>

<script>


    var index = 0;
    var partial = 0;
    var total = 1;
    var active = -1;
    var name = 0;
    var email = 0;
    var type = 0;

    function openModal() {
        $('#modal').modal('show');
        $('#message').hide();
        document.getElementById('addUser').reset();
    }

    function openModalEdit(id) {

        document.getElementById('addUser').reset();
        document.getElementById('userId').value = id;
        $('#modal').modal('show');
        $('#message').hide();
        if (id > 0) {
            showLoading();
            fetch(`<?= BASEURL ?>users/api/${id}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    json = json.message[0];
                    closeLoading();
                    document.getElementById('emailEdit').value = json.email;
                    document.getElementById('userIdEdit').value = json.id;
                    document.getElementById('typeEdit').value = json.type;
                    document.getElementById('nameEdit').value = json.name;
                    document.getElementById('activeEdit').value = json.active;
                });
            });
        }
    }

    const formAddUser = document.getElementById('addUser');
    const divMessage = document.getElementById('message');

    formAddUser.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let formData = formDataToJson('addUser');
        fetch("<?= BASEURL ?>users/register", {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            closeLoading();
            divMessage.classList.add("alert-danger");
            divMessage.classList.remove("alert-success");
            response.json().then(json => {
                divMessage.textContent = json.message;
                divMessage.style.display = 'block';
                if (response.status === 201) {
                    $('#modal').modal('hide');
                    divMessage.classList.add("alert-success");
                    divMessage.classList.remove("alert-danger");
                    formAddUser.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        name = formData.name;
        type = formData.type;
        $("#usersTable tbody").empty();
        generateTable();
    });

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        active = -1;
        name = 0;
        email = 0;
        type = 0;
        $("#usersTable tbody").empty();
        generateTable();
    }

    function generateUsersTable(user) {
        let actions = '';
        actions += `<i class="fa fa-pencil text-info" title="Edit" onclick="openModalEdit(${user.id})"></i> `;
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td class="text-center">${user.name}</td>
                    <td class="text-center">${typeStr(user.type)}</td>
                    <td class="text-center">${user.email}</td>
                    <td class="text-center">${activeStr(user.active)}</td>
                    ${actions}
                </tr>`;
    }

    function typeStr(type) {
        if (type == 1) {
            return 'Master';
        } else if (type == 2) {
            return 'Admin';
        } else if (type == 3) {
            return 'Manager';
        } else if (type == 4) {
            return 'Advisor';
        } else if (type == 5) {
            return 'Human Resources';
        }
    }

    function activeStr(active) {
        if (active == 1) {
            return 'Active';
        } else {
            return 'Inactive';
        }
    }

    function generateTable() {
        if (total > partial) {
            $('#loader').show();
            fetch(`<?= BASEURL ?>users/api/?index=${index}&name=${name}&email=${email}&type=${type}&active=${active}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#loader').hide();
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    let options = json.message.map(generateUsersTable);
                    $("#usersTable tbody").append(options);
                });
            });
        }
    }

    function selectManager() {
        var userType = document.getElementById('typeEdit').value;
        document.getElementById('userManager').style.display = 'none';

        if (userType == 4) {
            document.getElementById('userManager').style.display = 'block';
        }
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });
</script>
