<div class="row">
    <div class="col">
        <div class="card p-3">
            <h5 class="title">Detalhes do Gabinete</h5>
            <form id="register" method="post">
                <div class="form-group">
                    <input type="hidden" name="id" value="<?= $cabinetDetails ? $cabinetDetails->getId() : 0 ?>">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="email">E-mail Oficial</label>
                            <input id="email" name="email" class="form-control" type="text" placeholder="E-mail Oficial"
                                   value="<?= $cabinetDetails ? $cabinetDetails->getEmail() : '' ?>"  >
                        </div>
                        <div class="col-md-6">
                            <label for="city">Cidade</label>
                            <input id="city" name="city" class="form-control" type="text" placeholder="Cidade"
                                   value="<?= $cabinetDetails ? $cabinetDetails->getCity() : '' ?>"  >
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="header">Cabeçalho dos Documentos</label>
                            <textarea   id="header" name="header" rows="15" class="w-100"><?= $cabinetDetails ? $cabinetDetails->getHeader()  : '' ?></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="footer">Rodapé dos Documentos</label>
                            <textarea   id="footer" name="footer" rows="15" class="w-100"><?= $cabinetDetails ? $cabinetDetails->getFooter()  : '' ?></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="birthdayMessage">Mensagem de Aniversário</label>
                            <textarea   id="birthdayMessage" name="birthdayMessage" rows="15" class="w-100"><?= $cabinetDetails ? $cabinetDetails->getBirthdayMessage()  : '' ?></textarea>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary mt-4">Salvar</button>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div style="display: none" id="message" class="alert alert-danger" role="alert"></div>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

<script src="<?= BASEURL ?>assets/js/plugins/tinymce/jquery.tinymce.min.js"></script>
<script src="<?= BASEURL ?>assets/js/plugins/tinymce/tinymce.min.js"></script>
<script>tinymce.init({
        selector: "textarea",
        menubar: false,
        statusbar: false,
        toolbar: 'styleselect | bold italic | fontsizeselect | alignleft aligncenter alignright alignjustify | bullist numlist | link image media | forecolor backcolor table',
        plugins: ["lists link image media textcolor table"],
        browser_spellcheck: true,
        imagetools_cors_hosts: ['www.tinymce.com', 'codepen.io'],
        setup: function (editor) {
            editor.on('change', function () {
                editor.save();
            });
        }
    });
</script>

<script>

    const formAdd = document.getElementById('register');
    const divMessage = document.getElementById('message');

    formAdd.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let formData = formDataToJson('register');
        fetch("<?= BASEURL ?>gerenciar/detalhes_gabinete/cadastro", {
            method: 'POST',
            credentials: 'same-origin',
            headers: {//sempre igual
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            closeLoading();
            divMessage.classList.add("alert-danger");
            divMessage.classList.remove("alert-success");
            response.json().then(json => {
                //divMessage.innerHTML = json.message;
                divMessage.textContent = json.message;
                divMessage.style.display = 'block';
                if (response.status === 201) {
                    divMessage.classList.add("alert-success");
                    divMessage.classList.remove("alert-danger");
                    formAdd.reset();
                    setTimeout(function () {
                        window.location.href = "<?= BASEURL ?>gerenciar/detalhes_gabinete";
                    }, 1000);
                }
            });
        });
    });
</script>
