<div class="row">
    <div class="col">
        <div class="card p-3">
            <div class="row">
                <div class="col-md-8">
                    <h5 class="title">Intituições</h5>
                </div>
                <div class="col-md-4">
                    <a class="float-right btn btn-primary text-white" href="<?= BASEURL ?>gerenciar/instituicoes/cadastro"> Intituição <i
                            class="fa fa-plus"></i></a>
                </div>
            </div>
            <form id="filter">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="nameFilter">Nome</label>
                            <input class="form-control" id="nameFilter" name="name" type="text" placeholder="Nome">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="responsibleFilter">Responsável</label>
                            <input class="form-control" id="responsibleFilter" name="responsible" type="text" placeholder="Responsável">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="emailFilter">E-mail</label>
                            <input class="form-control" id="emailFilter" name="email" type="text" placeholder="E-mail">
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col text-right">
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Limpar</button>
                        <button class="btn btn-primary" type="submit">Filtrar</button>
                    </div>
                </div>
            </form>
            <p>Exibindo <span id="partial"></span> de <span id="total"></span> </p>
            <table class="table table-bordered table-striped" id="institutionsTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th class="text-center">Instituição</th>
                    <th class="text-center">Responsável</th>
                    <th class="text-center">Telefone</th>
                    <th class="text-center">E-mail</th>
                    <th class="text-center">Ações</th>
                </tr>
                </thead>
                <tbody></tbody>
            </table>
            <div style="display: none" id="message" class="alert alert-danger" role="alert"></div>
        </div>
    </div>
</div>
<script>

    var index = 0;
    var partial = 0;
    var total = 1;
    var phone = 0;
    var name = 0;
    var email = 0;
    var responsible = 0;

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        phone = formData.phone;
        name = formData.name;
        email = formData.email;
        responsible = formData.responsible;
        $("#institutionsTable tbody").empty();
        generateTable();
    })

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        phone = 0;
        name = 0;
        email = 0;
        responsible = 0;
        $("#institutionsTable tbody").empty();
        generateTable();
    }

    function edit(id) {

        return `<?= BASEURL?>gerenciar/instituicoes/cadastro/${id}`;

    }

    function generateInstitutionsTable(institutions) {
        let actions = '';
        actions += `<a href="${edit(institutions.id)}"><i class="fa fa-pencil text-info" title="Editar" ></i></a> `;
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td class="text-center">${institutions.name}</td>
                    <td class="text-center">${institutions.responsible}</td>
                    <td class="text-center">${institutions.phone}</td>
                    <td class="text-center">${institutions.email}</td>
                    ${actions}
                </tr>`;
    }


    function generateTable() {
        if (total > partial) {
            $('#loader').show();
            fetch(`<?= BASEURL ?>api/instituicoes/?index=${index}&name=${name}&email=${email}&responsible=${responsible}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#loader').hide();
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    let options = json.message.map(generateInstitutionsTable);
                    $("#institutionsTable tbody").append(options);
                });
            });
        }
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });
</script>
