<div class="row">
    <div class="col">
        <div class="card p-3">
            <div class="row">
                <div class="col-md-8">
                    <h5 class="title">Bairros</h5>
                </div>
                <div class="col-md-4">
                    <a class="float-right btn btn-primary text-white" href="#" onclick="openModal()"> Bairro <i
                            class="fa fa-plus"></i></a>
                </div>
            </div>
            <form id="filter">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="nameFilter">Bairro</label>
                            <input class="form-control" id="nameFilter" name="name" type="text" placeholder="Bairro">
                        </div>
                    </div>
                    <div class="col-md-6 text-right mt-3">
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Limpar</button>
                        <button class="btn btn-primary" type="submit">Filtrar</button>
                    </div>
                </div>
            </form>
            <p>Exibindo <span id="partial"></span> de <span id="total"></span> </p>
            <table class="table table-bordered table-striped mt-3" id="neighborhoodTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th class="text-center">Bairro</th>
                    <th class="text-center">Latitude</th>
                    <th class="text-center">Longitude</th>
                    <th class="text-center">Ações</th>
                </tr>
                </thead>
                <tbody></tbody>
            </table>
            <div style="display: none" id="message" class="alert alert-danger" role="alert"></div>
        </div>
    </div>
</div>

<!-- Modal Cadastro-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Cadastro de Bairro</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="addNeighborhoods">
                <div class="form-group">
                    <input type="hidden" name="neighborhoodsId" id="neighborhoodsId">
                    <div class="row">
                        <div class="col">
                            <label for="name">Bairro</label>
                            <input id="name" name="name" class="form-control" type="text" placeholder="Bairro" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="latitude">Latitude</label>
                            <input id="latitude" name="latitude" class="form-control" type="text" placeholder="Latitude">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="longitude">Longitude</label>
                            <input id="longitude" name="longitude" class="form-control" type="text" placeholder="Longitude">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Salvar Bairro</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>

    function openModal() {
        $('#modal').modal('show');
        $('#message').hide();
        document.getElementById('addNeighborhoods').reset();
    }

    const formAdd = document.getElementById('addNeighborhoods');
    const divMessage = document.getElementById('message');

    formAdd.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let formData = formDataToJson('addNeighborhoods');
        fetch("<?= BASEURL ?>gerenciar/bairros/cadastro", {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            closeLoading();
            divMessage.classList.add("alert-danger");
            divMessage.classList.remove("alert-success");
            response.json().then(json => {
                divMessage.textContent = json.message;
                divMessage.style.display = 'block';
                if (response.status === 201) {
                    $('#modal').modal('hide');
                    divMessage.classList.add("alert-success");
                    divMessage.classList.remove("alert-danger");
                    formAdd.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    var index = 0;
    var partial = 0;
    var total = 1;
    var name = 0;

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        latitude = formData.latitude;
        name = formData.name;
        longitude = formData.longitude;
        $("#neighborhoodTable tbody").empty();
        generateTable();
    });

    function openModalEdit(id) {

        document.getElementById('addNeighborhoods').reset();
        document.getElementById('neighborhoodsId').value = id;
        $('#modal').modal('show');
        $('#message').hide();
        if (id > 0) {
            showLoading();
            fetch(`<?= BASEURL ?>api/bairros/${id}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    json = json.message[0];
                    closeLoading();
                    document.getElementById('name').value = json.name;
                    document.getElementById('latitude').value = json.latitude;
                    document.getElementById('longitude').value = json.longitude;
                });
            });
        }
    }

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        name = 0;
        $("#neighborhoodTable tbody").empty();
        generateTable();
    }

    function generateInstitutionsTable(neighborhood) {
        let actions = '';
        actions += `<i class="fa fa-pencil text-info" title="Editar" onclick="openModalEdit(${neighborhood.id})"></i> `;
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td class="text-center">${neighborhood.name}</td>
                    <td class="text-center">${neighborhood.latitude}</td>
                    <td class="text-center">${neighborhood.longitude}</td>
                    ${actions}
                </tr>`;
    }


    function generateTable() {
        if (total > partial) {
            $('#loader').show();
            fetch(`<?= BASEURL ?>api/bairros/?index=${index}&name=${name}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#loader').hide();
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    let options = json.message.map(generateInstitutionsTable);
                    $("#neighborhoodTable tbody").append(options);
                });
            });
        }
    }

    $(document).ready(function () {
        generateTable();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateTable();
            }
        });
    });

</script>
