<div class="row">
    <div class="col">
        <div class="card p-3">
            <form id="filter">
                <div class="row">
                    <div class="col-md-2 my-auto">
                        <a class="btn btn-primary text-white" href="#" onclick="openModal()"><i
                                    class="fa fa-plus"></i> Deal</a>
                    </div>
                    <div class="col-md-4 my-auto">
                        <div class="form-group mt-2">
                            <input class="form-control" id="nameFilter" name="name" type="text" placeholder="Name">
                        </div>
                    </div>
                    <div class="col-md-3 my-auto">
                        <div class="form-group mt-2">
                            <select class="form-control" id="countryFilter" name="country" type="text">
                                <option value="0">Select Country</option>
                                <?php foreach ($countries as $country): ?>
                                    <option value="<?= $country->getId() ?>"><?= $country->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3 text-right">
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Cancel</button>
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="card">
            <div class="row mt-4">
                <div class="col">
                    <div class="row justify-content-between">
                        <div class="col-md-4 p-3">
                            <div class="row">
                                <div class="col bg-orange p-3">
                                    <h6 class="my-auto">Follow Up</h6>
                                </div>
                            </div>
                            <div id="status1" class="row bg-grey">
                                <div class="row bg-grey pb-5" id="cardDeal1" ondrop="drop(event, 'cardDeal1')"
                                     ondragover="allowDrop(event)" style="width: 100%">

                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 p-3">
                            <div class="row">
                                <div class="col bg-yellow p-3">
                                    <h6 class="my-auto">Pending Agreement</h6>
                                </div>
                            </div>
                            <div id="stauts2" class="row bg-grey">
                                <div class="row bg-grey pb-5" id="cardDeal2" ondrop="drop(event, 'cardDeal2')"
                                     ondragover="allowDrop(event)" style="width: 100%">

                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 p-3">
                            <div class="row">
                                <div class="col bg-green p-3">
                                    <h6 class="my-auto">Approved Terms</h6>
                                </div>
                            </div>
                            <div id="status3" class="row bg-grey colDrop">
                                <div class="row bg-grey pb-5" id="cardDeal3" ondrop="drop(event, 'cardDeal3')"
                                     ondragover="allowDrop(event)" style="width: 100%">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal Cadastro-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Deal registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-control" id="addDeal" method="post">
                <div class="form-group">
                    <input type="hidden" name="dealId" id="dealId">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="name">Name</label>
                            <input id="name" name="name" class="form-control" type="text" placeholder="Name">
                        </div>
                        <div class="col-md-6">
                            <label for="company">Company</label>
                            <input id="company" name="company" class="form-control" type="text"
                                   placeholder="Company">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="email">Email</label>
                            <input id="email" name="email" class="form-control" type="email" placeholder="Email">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="phone">Phone</label>
                            <input id="phone" name="phone" class="form-control" type="text"
                                   placeholder="+99 99 9999-9999">
                        </div>
                        <div class="col-md-4">
                            <label for="status">Status</label>
                            <select id="status" name="status" class="form-control">
                                <option value="0">Select</option>
                                <option value="1">Follow Up</option>
                                <option value="2">Pending Agreement</option>
                                <option value="3">Approved Terms</option>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label for="office">Office</label>
                            <input id="office" name="office" class="form-control" type="text" placeholder="Office">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" class="btn btn-primary">Save Deal</button>
                    </div>
                </div>
                <div style="display: none" id="message" class="alert alert-danger" role="alert"></div>
            </form>
        </div>
    </div>
</div>

<script>

    function openModal() {
        $('#modal').modal('show');
        $('#message').hide();
        document.getElementById('addDeal').reset();
    }

    const formAdd = document.getElementById('addDeal');
    const divMessage = document.getElementById('message');

    formAdd.addEventListener('submit', e => {
        e.preventDefault();
        showLoading();
        let formData = formDataToJson('addDeal');
        fetch("<?= BASEURL ?>deals/register", {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            closeLoading();
            divMessage.classList.add("alert-danger");
            divMessage.classList.remove("alert-success");
            response.json().then(json => {
                divMessage.textContent = json.message;
                divMessage.style.display = 'block';
                if (response.status === 201) {
                    $('#modal').modal('hide');
                    divMessage.classList.add("alert-success");
                    divMessage.classList.remove("alert-danger");
                    formAdd.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                }
            });
        });
    });

    var index = 0;
    var partial = 0;
    var total = 1;
    var name = 0;
    var country = 0;

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        name = formData.name;
        country = formData.country;
        $("#cardDeal1 tbody").empty();
        $("#cardDeal2 tbody").empty();
        $("#cardDeal3 tbody").empty();
        generateDeals();
    });

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        name = 0;
        country = 0;
        $("#cardDeal1 tbody").empty();
        $("#cardDeal2 tbody").empty();
        $("#cardDeal3 tbody").empty();
        generateDeals();
    }

    function generateDealsCard1(deal) {
        if (deal.status == 1)

            return `<div id="${deal.id}" draggable="true" class="mx-2" ondragstart="drag(event)" style="width: 100%">
                        <a href="${viewDeal(deal.id)}" style="text-decoration: none">
                            <div class="bg-white mt-3 p-2">
                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="row deal-title"><b>${deal.name}</b></div>
                                        <div class="row deal-sub">${deal.company}</div>
                                    </div>
                                    <div class="col-md-2 my-auto">
                                        <i class="fa fa-check-circle"></i>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>`;
    }

    function generateDealsCard2(deal) {
        if (deal.status == 2)

            return `<div id="${deal.id}" draggable="true" class="mx-2" ondragstart="drag(event)" style="width: 100%">
                        <a href="${viewDeal(deal.id)}" style="text-decoration: none">
                            <div class="bg-white mx-1 mt-3 p-2" >
                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="row deal-title"><b>${deal.name}</b></div>
                                        <div class="row deal-sub" style="color: grey">${deal.company}</div>
                                    </div>
                                    <div class="col-md-2 my-auto">
                                        <i class="fa fa-check-circle"></i>
                                    </div>
                                </div>
                            </div>
                        </a>
                    <div>`;
    }

    function generateDealsCard3(deal) {
        if (deal.status == 3)

            return `<div id="${deal.id}" draggable="true" class="mx-2" ondragstart="drag(event)" style="width: 100%">
                        <a href="${viewDeal(deal.id)}" style="text-decoration: none">
                            <div class="bg-white mx-1 mt-3 p-2">
                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="row deal-title"><b>${deal.name}</b></div>
                                        <div class="row deal-sub">${deal.company}</div>
                                    </div>
                                    <div class="col-md-2 my-auto">
                                        <i class="fa fa-check-circle"></i>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>`;
    }

    function allowDrop(ev) {
        ev.preventDefault();
    }

    function drag(ev) {
        ev.dataTransfer.setData("text", ev.target.id);
    }

    function drop(ev, id) {
        ev.preventDefault();
        var data = ev.dataTransfer.getData("text");
        document.getElementById(id).appendChild(document.getElementById(data));

        var status = id;
        var statusInt = status.substr(-1);
        updateStatus(data, statusInt);
    }

    function updateStatus(deal, status) {
        fetch(`<?= BASEURL ?>deals/update/api/?deal=${deal}&status=${status}`, {
            method: "GET",
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        })
    }

    function viewDeal(id) {
        return `<?= BASEURL ?>deals/${id}`
    }

    function generateDeals() {
        if (total > partial) {
            $('#loader').show();
            fetch(`<?= BASEURL ?>deals/api/?index=${index}&name=${name}&country=${country}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#loader').hide();
                    let status1 = json.message.map(generateDealsCard1);
                    let status2 = json.message.map(generateDealsCard2);
                    let status3 = json.message.map(generateDealsCard3);
                    $("#cardDeal1").append(status1);
                    $("#cardDeal2").append(status2);
                    $("#cardDeal3").append(status3);
                });
            });
        }
    }

    $(document).ready(function () {
        generateDeals();
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                index++;
                generateDeals();
            }
        });
    });

</script>
