<div class="row">
    <div class="col">
        <div class="row">
            <div class="col-md-7">
                <div class="card p-3">
                    <div class="row pb-5">
                        <div class="col">
                            <h6 class="title ml-5">activity history</h6>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-2 text-center">
                            <i class="fa fa-2x fa-phone"></i>
                        </div>
                        <div class="col-md-10">
                            <div class="row">
                                Call
                            </div>
                            <div class="row">
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                                23/02/2021 09:51 Diego Werlich<br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="card p-3" style="background: #004FC5">
                    <div class="row text-white">
                        <div class="row">
                            <i class="fa fa-2x fa-user p-2"></i> <h5
                                    class="title mr-4 my-auto"> <?= $client->getName() ?></h5><br>
                        </div>
                        <div class="row">
                            <i class="fa fa-2x fa-city p-2"></i><span
                                    class="my-auto mr-4"><?= $client->getCompany() ?></span>
                        </div>
                        <div class="row">
                            <i class="fa fa-2x fa-phone p-2"></i><span
                                    class="my-auto mr-4"><?= $client->getPhone() ?></span>
                        </div>
                        <div class="row">
                            <i class="fa fa-2x fa-envelope p-2"></i><span
                                    class="my-auto"><?= $client->getEmail() ?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>