<div class="row">
    <div class="col">
        <div class="card p-3">
            <div class="row">
                <div class="col">
                    <div class="row">
                        <i class="fa fa-2x fa-user p-2"></i> <h5
                                class="title mr-4 my-auto"> <?= $deal->getName() ?></h5>
                        <i class="fa fa-2x fa-city p-2"></i><span class="my-auto mr-4"><?= $deal->getCompany() ?></span>
                        <i class="fa fa-2x fa-phone p-2"></i><span class="my-auto mr-4"><?= $deal->getPhone() ?></span>
                        <i class="fa fa-2x fa-envelope p-2"></i><span class="my-auto"><?= $deal->getEmail() ?></span>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>